-- Automatic content generation schedule on social_content_configs
ALTER TABLE "social_content_configs"
  ADD COLUMN IF NOT EXISTS "autoGenerateEnabled" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "autoGenerateDaysOfWeek" INTEGER[] NOT NULL DEFAULT ARRAY[]::INTEGER[],
  ADD COLUMN IF NOT EXISTS "autoGenerateTime" TEXT NOT NULL DEFAULT '10:00',
  ADD COLUMN IF NOT EXISTS "autoGenerateChannels" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS "autoGenerateObjective" TEXT NOT NULL DEFAULT 'AUTOMATIC',
  ADD COLUMN IF NOT EXISTS "lastAutoGenerateAt" TIMESTAMP(3);
