'use client';

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { api, apiForm } from '@/lib/api';
import { ContentKnowledgePanel } from '@/components/content-knowledge-panel';

// Feature flag — ocultar voces ElevenLabs hasta contratar plan pago (previews y más voces requieren plan)
// Poné en true o NEXT_PUBLIC_ELEVENLABS_ENABLED=true para habilitar
const ELEVENLABS_ENABLED =
  (process.env.NEXT_PUBLIC_ELEVENLABS_ENABLED ?? '').trim().toLowerCase() === 'true';

interface ContentAsset {
  id: string;
  type?: string;
  role?: string | null;
  format: string;
  storageUrl: string;
  width?: number | null;
  height?: number | null;
  provider?: string | null;
  model?: string | null;
}

interface GeneratedContent {
  id: string;
  status: string;
  objective: string;
  channels: string[];
  mediaType?: string;
  topic?: string | null;
  headline?: string | null;
  hook?: string | null;
  caption?: string | null;
  cta?: string | null;
  hashtags?: string[];
  autoEditStatus?: string | null;
  autoEditError?: string | null;
  error?: string | null;
  createdAt: string;
  referenceImageUrls?: string[];
  assets: ContentAsset[];
  publications?: ContentPublication[];
  service?: { id: string; name: string } | null;
}

interface ContentPublication {
  id: string;
  channel: string;
  status: string;
  externalId?: string | null;
  error?: string | null;
  publishedAt?: string | null;
}

interface ContentSummary {
  generatedThisMonth: number;
  published: number;
  scheduled: number;
  drafts: number;
  failed: number;
  imageGenerationsThisMonth: number;
  videoGenerationsThisMonth?: number;
  estimatedCostThisMonth: number;
}

interface SocialContentConfig {
  id: string;
  autoGenerateEnabled: boolean;
  autoGenerateDaysOfWeek: number[];
  autoGenerateTime: string;
  autoGenerateChannels: string[];
  autoGenerateObjective: string;
  notifyWhatsAppPhone?: string | null;
  notifyEmail?: string | null;
  lastAutoGenerateAt?: string | null;
  defaultChannels: string[];
  preferredVideoProvider?: string | null;
  preferredVideoModel?: string | null;
}

interface WhatsAppStatus {
  status: string;
}

interface SocialListResponse {
  configured: boolean;
  connections: Array<{
    platform: 'instagram' | 'tiktok' | 'facebook';
    status: string;
  }>;
}

const WEEKDAYS = [
  { value: 1, label: 'Lun' },
  { value: 2, label: 'Mar' },
  { value: 3, label: 'Mié' },
  { value: 4, label: 'Jue' },
  { value: 5, label: 'Vie' },
  { value: 6, label: 'Sáb' },
  { value: 7, label: 'Dom' },
] as const;

interface ServiceRow {
  id: string;
  name: string;
  enabled: boolean;
}

interface ReferencePreview {
  id: string;
  file?: File;
  url: string;
  local: boolean;
}

const OBJECTIVES = [
  { value: 'AUTOMATIC', label: 'Automático' },
  { value: 'SERVICE_PROMOTION', label: 'Promoción de servicio' },
  { value: 'OFFER', label: 'Oferta' },
  { value: 'TIP', label: 'Consejo / tip' },
  { value: 'INFO', label: 'Informativo' },
  { value: 'SPECIAL_DATE', label: 'Fecha especial' },
  { value: 'CUSTOM', label: 'Personalizado' },
] as const;

const CONTENT_STYLES = [
  { value: 'AUTO', label: 'Detectar (Educativo / Comedia / Venta)' },
  { value: 'EDUCATIONAL', label: 'Educativo' },
  { value: 'COMEDY', label: 'Comedia' },
  { value: 'SALES', label: 'Venta' },
] as const;

const CHANNELS = [
  { value: 'WHATSAPP_STATUS', label: 'WhatsApp Status' },
  { value: 'INSTAGRAM_STORY', label: 'Instagram Story' },
  { value: 'INSTAGRAM_FEED', label: 'Instagram Feed' },
  { value: 'FACEBOOK_STORY', label: 'Facebook Story' },
  { value: 'FACEBOOK_FEED', label: 'Facebook Feed' },
] as const;

const VIDEO_CHANNELS = [
  { value: 'INSTAGRAM_REEL', label: 'Instagram Reel' },
  { value: 'INSTAGRAM_STORY', label: 'Instagram Story' },
  { value: 'FACEBOOK_REEL', label: 'Facebook Reel' },
  { value: 'FACEBOOK_STORY', label: 'Facebook Story' },
  { value: 'WHATSAPP_STATUS', label: 'WhatsApp Status' },
  { value: 'TIKTOK', label: 'TikTok' },
] as const;

const AUTO_CHANNELS = [
  ...CHANNELS,
  { value: 'INSTAGRAM_REEL', label: 'Instagram Reel' },
  { value: 'FACEBOOK_REEL', label: 'Facebook Reel' },
  { value: 'TIKTOK', label: 'TikTok' },
] as const;

const CHANNEL_LABEL: Record<string, string> = {
  WHATSAPP_STATUS: 'WhatsApp Status',
  INSTAGRAM_STORY: 'Instagram Story',
  INSTAGRAM_FEED: 'Instagram Feed',
  INSTAGRAM_REEL: 'Instagram Reel',
  FACEBOOK_STORY: 'Facebook Story',
  FACEBOOK_FEED: 'Facebook Feed',
  FACEBOOK_REEL: 'Facebook Reel',
  TIKTOK: 'TikTok',
};

const VIDEO_DURATIONS = [5, 10, 15] as const;

const STATUS_LABEL: Record<string, string> = {
  DRAFT: 'Borrador',
  READY: 'Listo',
  GENERATING: 'Generando…',
  PUBLISHING: 'Publicando…',
  SCHEDULED: 'Programado',
  PUBLISHED: 'Publicado',
  PARTIALLY_PUBLISHED: 'Parcial',
  FAILED: 'Error',
};

function statusClass(status: string) {
  if (
    status === 'READY' ||
    status === 'DRAFT' ||
    status === 'PUBLISHED'
  ) {
    return 'badge-success';
  }
  if (status === 'PARTIALLY_PUBLISHED') return 'bg-amber-500/15 text-amber-700';
  if (status === 'GENERATING') return 'bg-accent/15 text-accent';
  if (status === 'PUBLISHING') return 'bg-accent/15 text-accent';
  if (status === 'FAILED') return 'bg-red-500/15 text-red-600';
  return 'badge-muted';
}

function BusySpinner({ className = 'h-5 w-5' }: { className?: string }) {
  return (
    <span
      className={`inline-block shrink-0 animate-spin rounded-full border-2 border-accent/25 border-t-accent ${className}`}
      aria-hidden
    />
  );
}

const AUTO_EDIT_LABEL: Record<string, string> = {
  PROCESSING: 'Autoeditando…',
  COMPLETED: 'Listo para publicar',
  SKIPPED: 'Sin overlays',
  FAILED: 'Autoedición fallida',
};

function autoEditClass(status?: string | null) {
  if (status === 'COMPLETED') return 'badge-success';
  if (status === 'SKIPPED') return 'badge-muted';
  if (status === 'PROCESSING') return 'badge-muted';
  if (status === 'FAILED') return 'bg-amber-500/15 text-amber-700';
  return 'badge-muted';
}

function assetRoleLabel(asset: ContentAsset, isVideo: boolean): string {
  if (!isVideo) return asset.format;
  if (asset.role === 'EDITED') return 'Video final';
  if (asset.role === 'ORIGINAL') return 'Sin editar';
  return asset.format;
}

function previewThumb(item: GeneratedContent): ContentAsset | undefined {
  return (
    item.assets?.find((asset) => asset.role === 'EDITED') ?? item.assets?.[0]
  );
}

function formatPubDate(value?: string | null) {
  if (!value) return null;
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return null;
  const dd = String(date.getDate()).padStart(2, '0');
  const mm = String(date.getMonth() + 1).padStart(2, '0');
  const yyyy = date.getFullYear();
  return `${dd}/${mm}/${yyyy}`;
}

function apiErrorMessage(error: unknown, fallback: string) {
  const raw = error instanceof Error ? error.message : '';
  try {
    const parsed = JSON.parse(raw) as { message?: unknown };
    if (typeof parsed.message === 'string' && parsed.message.trim()) {
      return parsed.message;
    }
  } catch {
    // texto plano
  }
  return raw || fallback;
}

function isVideoContent(item: GeneratedContent): boolean {
  if ((item.mediaType ?? 'IMAGE').toUpperCase() === 'VIDEO') return true;
  const assets = item.assets ?? [];
  if (!assets.length) return false;
  return assets.some((asset) => (asset.type ?? 'IMAGE').toUpperCase() === 'VIDEO');
}

function isImageContent(item: GeneratedContent): boolean {
  if ((item.mediaType ?? 'IMAGE').toUpperCase() === 'VIDEO') return false;
  if (item.status === 'GENERATING' || item.status === 'PUBLISHING') {
    return !isVideoContent(item);
  }
  const assets = item.assets ?? [];
  if (!assets.length) return false;
  return assets.every((asset) => (asset.type ?? 'IMAGE').toUpperCase() !== 'VIDEO');
}

interface LightboxMedia {
  url: string;
  video: boolean;
  label?: string;
}

function LightboxVideo({ src, label }: { src: string; label?: string }) {
  const ref = useRef<HTMLVideoElement>(null);

  useEffect(() => {
    const video = ref.current;
    if (!video) return;

    const exitNativeFullscreen = () => {
      const webkitVideo = video as HTMLVideoElement & {
        webkitDisplayingFullscreen?: boolean;
        webkitExitFullscreen?: () => void;
      };
      if (webkitVideo.webkitDisplayingFullscreen) {
        webkitVideo.webkitExitFullscreen?.();
      }
      if (document.fullscreenElement === video) {
        void document.exitFullscreen();
      }
    };

    const onBegin = () => exitNativeFullscreen();
    const onChange = () => {
      if (document.fullscreenElement === video) exitNativeFullscreen();
    };

    video.addEventListener('webkitbeginfullscreen', onBegin);
    document.addEventListener('fullscreenchange', onChange);
    return () => {
      video.removeEventListener('webkitbeginfullscreen', onBegin);
      document.removeEventListener('fullscreenchange', onChange);
    };
  }, [src]);

  return (
    <video
      ref={ref}
      src={src}
      className="video-no-fullscreen max-h-[88vh] max-w-[min(96vw,560px)] w-auto h-auto rounded-xl shadow-2xl bg-black object-contain"
      controls
      autoPlay
      playsInline
      controlsList="nofullscreen nodownload noremoteplayback"
      disablePictureInPicture
      aria-label={label || 'Video generado'}
    />
  );
}

function MediaLightbox({
  media,
  onClose,
}: {
  media: LightboxMedia;
  onClose: () => void;
}) {
  useEffect(() => {
    function onKey(event: KeyboardEvent) {
      if (event.key === 'Escape') onClose();
    }
    window.addEventListener('keydown', onKey);
    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    return () => {
      window.removeEventListener('keydown', onKey);
      document.body.style.overflow = previousOverflow;
    };
  }, [onClose]);

  return (
    <div
      role="dialog"
      aria-modal="true"
      aria-label={media.label || 'Vista ampliada'}
      className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-8"
      onClick={onClose}
    >
      <div className="absolute inset-0 bg-black/82" />
      <button
        type="button"
        onClick={onClose}
        className="absolute top-4 right-4 z-20 rounded-full bg-white/15 hover:bg-white/25 text-white w-10 h-10 inline-flex items-center justify-center text-lg"
        aria-label="Cerrar"
      >
        ×
      </button>
      <div
        className="relative z-10 max-h-[92vh] max-w-[min(96vw,1120px)]"
        onClick={(event) => event.stopPropagation()}
      >
        {media.video ? (
          <LightboxVideo src={media.url} label={media.label} />
        ) : (
          // eslint-disable-next-line @next/next/no-img-element
          <img
            src={media.url}
            alt={media.label || 'Imagen generada'}
            className="max-h-[92vh] max-w-full rounded-xl shadow-2xl object-contain bg-black"
          />
        )}
      </div>
    </div>
  );
}

export function ContentCreator() {
  const queryClient = useQueryClient();
  const [objective, setObjective] = useState<string>('AUTOMATIC');
  const [contentStyle, setContentStyle] = useState<string>('AUTO');
  const [channels, setChannels] = useState<string[]>([
    'INSTAGRAM_FEED',
    'INSTAGRAM_STORY',
  ]);
  const [instructions, setInstructions] = useState('');
  const [serviceId, setServiceId] = useState('');
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [editCaption, setEditCaption] = useState('');
  const [editHeadline, setEditHeadline] = useState('');
  const [editCta, setEditCta] = useState('');
  const [editHashtags, setEditHashtags] = useState('');
  const [references, setReferences] = useState<ReferencePreview[]>([]);
  const [publishChannels, setPublishChannels] = useState<string[]>([]);

  const [autoEnabled, setAutoEnabled] = useState(false);
  const [autoDays, setAutoDays] = useState<number[]>([1, 2, 3, 4, 5]);
  const [autoTime, setAutoTime] = useState('10:00');
  const [autoChannels, setAutoChannels] = useState<string[]>([
    'INSTAGRAM_STORY',
    'INSTAGRAM_FEED',
  ]);
  const [autoObjective, setAutoObjective] = useState('AUTOMATIC');
  const [notifyWhatsAppPhone, setNotifyWhatsAppPhone] = useState('');
  const [notifyEmail, setNotifyEmail] = useState('');
  const [autoDirty, setAutoDirty] = useState(false);
  const [mediaKind, setMediaKind] = useState<'image' | 'video'>('image');
  const [videoDuration, setVideoDuration] = useState<5 | 10 | 15>(5);
  const [videoProvider, setVideoProvider] = useState('');
  const [videoModel, setVideoModel] = useState('');
  const [preferredVideoProvider, setPreferredVideoProvider] = useState('');
  const [preferredVideoModel, setPreferredVideoModel] = useState('');
  const [videoGenerateAudio, setVideoGenerateAudio] = useState(true);
  const [lightbox, setLightbox] = useState<LightboxMedia | null>(null);
  const [workspace, setWorkspace] = useState<
    'create' | 'library' | 'schedule' | 'guidelines'
  >('create');
  const [pieceTab, setPieceTab] = useState<'edit' | 'publish'>('edit');

  const summary = useQuery({
    queryKey: ['content-summary'],
    queryFn: () => api<ContentSummary>('/admin/content/summary'),
  });

  const socialConfig = useQuery({
    queryKey: ['content-config'],
    queryFn: () => api<SocialContentConfig>('/admin/content/config'),
  });

  const list = useQuery({
    queryKey: ['content-list'],
    queryFn: () => api<GeneratedContent[]>('/admin/content'),
    refetchInterval: (query) =>
      (query.state.data ?? []).some(
        (item) =>
          item.status === 'GENERATING' ||
          item.status === 'PUBLISHING' ||
          item.autoEditStatus === 'PROCESSING',
      )
        ? 4000
        : false,
  });

  const business = useQuery({
    queryKey: ['current-business'],
    queryFn: () =>
      api<{ brandingConfig?: unknown | null; timezone?: string }>(
        '/admin/business',
      ),
  });

  const whatsapp = useQuery({
    queryKey: ['whatsapp-config'],
    queryFn: () => api<WhatsAppStatus | null>('/admin/whatsapp'),
  });
  const waConnected = whatsapp.data?.status === 'connected';

  const social = useQuery({
    queryKey: ['social-connections'],
    queryFn: () => api<SocialListResponse>('/admin/social'),
  });
  const igPublishConnected = social.data?.connections.some(
    (item) => item.platform === 'instagram' && item.status === 'connected',
  );
  const tiktokConnected = social.data?.connections.some(
    (item) => item.platform === 'tiktok' && item.status === 'connected',
  );
  const facebookConnected = social.data?.connections.some(
    (item) => item.platform === 'facebook' && item.status === 'connected',
  );

  const servicesQuery = useQuery({
    queryKey: ['services', 'enabled'],
    queryFn: () =>
      api<ServiceRow[]>('/admin/services?enabledOnly=true'),
  });

  const [hydratedConfigId, setHydratedConfigId] = useState<string | null>(null);
  const autoConfig = socialConfig.data;
  if (autoConfig && !autoDirty && autoConfig.id !== hydratedConfigId) {
    setHydratedConfigId(autoConfig.id);
    setAutoEnabled(Boolean(autoConfig.autoGenerateEnabled));
    setAutoDays(
      autoConfig.autoGenerateDaysOfWeek?.length > 0
        ? autoConfig.autoGenerateDaysOfWeek
        : [1, 2, 3, 4, 5, 6, 7],
    );
    setAutoTime(autoConfig.autoGenerateTime || '10:00');
    setAutoChannels(
      autoConfig.autoGenerateChannels?.length > 0
        ? autoConfig.autoGenerateChannels
        : autoConfig.defaultChannels?.length > 0
          ? autoConfig.defaultChannels
          : ['INSTAGRAM_STORY', 'INSTAGRAM_FEED'],
    );
    setAutoObjective(autoConfig.autoGenerateObjective || 'AUTOMATIC');
    setNotifyWhatsAppPhone(autoConfig.notifyWhatsAppPhone || '');
    setNotifyEmail(autoConfig.notifyEmail || '');
    setPreferredVideoProvider(autoConfig.preferredVideoProvider || '');
    setPreferredVideoModel(autoConfig.preferredVideoModel || '');
  }

  const selected = useQuery({
    queryKey: ['content', selectedId],
    enabled: Boolean(selectedId),
    queryFn: () => api<GeneratedContent>(`/admin/content/${selectedId}`),
    refetchInterval: (query) => {
      const item = query.state.data;
      if (
        item?.status === 'GENERATING' ||
        item?.status === 'PUBLISHING' ||
        item?.autoEditStatus === 'PROCESSING'
      ) {
        return 4000;
      }
      return false;
    },
  });

  const detail = selected.data ?? list.data?.find((c) => c.id === selectedId);

  function syncEditors(item: GeneratedContent | undefined) {
    if (!item) return;
    setEditCaption(item.caption ?? '');
    setEditHeadline(item.headline ?? '');
    setEditCta(item.cta ?? '');
    setEditHashtags((item.hashtags ?? []).join(' '));
    setPublishChannels(
      item.channels?.length ? [...item.channels] : ['INSTAGRAM_FEED'],
    );
  }

  function openContent(item: GeneratedContent) {
    setWorkspace('library');
    setPieceTab('edit');
    setSelectedId(item.id);
    syncEditors(item);
    setReferences((prev) => {
      for (const ref of prev) {
        if (ref.local) URL.revokeObjectURL(ref.url);
      }
      return (item.referenceImageUrls ?? []).map((url, index) => ({
        id: `saved-${item.id}-${index}`,
        url,
        local: false,
      }));
    });
  }

  function addReferenceFiles(fileList: FileList | null) {
    if (!fileList?.length) return;
    const incoming = Array.from(fileList).filter((f) =>
      f.type.startsWith('image/'),
    );
    setReferences((prev) => {
      const room = Math.max(0, 4 - prev.length);
      const next = incoming.slice(0, room).map((file) => ({
        id: `local-${file.name}-${file.size}-${file.lastModified}`,
        file,
        url: URL.createObjectURL(file),
        local: true,
      }));
      return [...prev, ...next].slice(0, 4);
    });
  }

  function removeReference(id: string) {
    setReferences((prev) => {
      const target = prev.find((r) => r.id === id);
      if (target?.local) URL.revokeObjectURL(target.url);
      return prev.filter((r) => r.id !== id);
    });
  }

  async function resolveReferenceUrls(): Promise<string[]> {
    const alreadyUploaded = references
      .filter((r) => !r.local)
      .map((r) => r.url);
    const locals = references.filter((r) => r.local && r.file);
    if (!locals.length) return alreadyUploaded;

    const form = new FormData();
    for (const ref of locals) {
      if (ref.file) form.append('files', ref.file);
    }
    const uploaded = await apiForm<{ urls: string[] }>(
      '/admin/content/references',
      form,
    );
    return [...alreadyUploaded, ...(uploaded.urls ?? [])].slice(0, 4);
  }

  const generate = useMutation({
    mutationFn: async (payload: {
      objective: string;
      channels: string[];
      userInstructions?: string;
      serviceId?: string;
      contentId?: string;
      contentStyle?: string;
    }) => {
      const referenceImageUrls = await resolveReferenceUrls();
      return api<GeneratedContent>('/admin/content/generate', {
        method: 'POST',
        body: JSON.stringify({
          ...payload,
          contentStyle: payload.contentStyle ?? contentStyle,
          referenceImageUrls,
          mediaType: mediaKind === 'video' ? 'VIDEO' : 'IMAGE',
          ...(mediaKind === 'video'
            ? {
                durationSeconds: videoDuration,
                ...(videoProvider ? { videoProvider } : {}),
                ...(videoModel ? { videoModel } : {}),
                generateAudio: videoGenerateAudio,
              }
            : {}),
        }),
      });
    },
    onSuccess: async (data) => {
      setWorkspace('library');
      setPieceTab('edit');
      setSelectedId(data.id);
      syncEditors(data);
      setReferences(
        (data.referenceImageUrls ?? []).map((url, index) => ({
          id: `saved-${data.id}-${index}`,
          url,
          local: false,
        })),
      );
      await queryClient.invalidateQueries({ queryKey: ['content-list'] });
      await queryClient.invalidateQueries({ queryKey: ['content-summary'] });
      await queryClient.invalidateQueries({ queryKey: ['content', data.id] });
    },
  });

  const suggestBrief = useMutation({
    mutationFn: async () => {
      return api<{ instructions: string }>('/admin/content/suggest-brief', {
        method: 'POST',
        body: JSON.stringify({
          objective,
          channels,
          userInstructions: instructions.trim() || undefined,
          serviceId: serviceId || undefined,
          contentStyle,
          mediaType: mediaKind === 'video' ? 'VIDEO' : 'IMAGE',
          ...(mediaKind === 'video' ? { durationSeconds: videoDuration } : {}),
        }),
      });
    },
    onSuccess: (data) => {
      setInstructions(data.instructions);
    },
  });

  const saveDraft = useMutation({
    mutationFn: async () => {
      if (!selectedId) throw new Error('Sin contenido');
      await api(`/admin/content/${selectedId}`, {
        method: 'PATCH',
        body: JSON.stringify({
          caption: editCaption,
          headline: editHeadline,
          cta: editCta,
          hashtags: editHashtags.split(/[\s,]+/).filter(Boolean),
        }),
      });
      return api(`/admin/content/${selectedId}/draft`, { method: 'POST' });
    },
    onSuccess: async () => {
      await queryClient.invalidateQueries({ queryKey: ['content-list'] });
      await queryClient.invalidateQueries({ queryKey: ['content', selectedId] });
      await queryClient.invalidateQueries({ queryKey: ['content-summary'] });
    },
  });

  const remove = useMutation({
    mutationFn: (id: string) =>
      api(`/admin/content/${id}`, { method: 'DELETE' }),
    onSuccess: async (_, id) => {
      if (selectedId === id) setSelectedId(null);
      await queryClient.invalidateQueries({ queryKey: ['content-list'] });
      await queryClient.invalidateQueries({ queryKey: ['content-summary'] });
    },
  });

  const autoEdit = useMutation({
    mutationFn: async () => {
      if (!selectedId) throw new Error('Sin contenido');
      return api<GeneratedContent>(`/admin/content/${selectedId}/auto-edit`, {
        method: 'POST',
        body: JSON.stringify({
          headline: editHeadline,
          cta: editCta,
        }),
      });
    },
    onSuccess: async (data) => {
      syncEditors(data);
      queryClient.setQueryData(['content', data.id], data);
      await queryClient.invalidateQueries({ queryKey: ['content-list'] });
      await queryClient.invalidateQueries({ queryKey: ['content', data.id] });
    },
  });

  const publish = useMutation({
    mutationFn: async () => {
      if (!selectedId || !detail) throw new Error('Sin contenido');
      const channels =
        publishChannels.length > 0 ? publishChannels : detail.channels;
      if (!channels.length) {
        throw new Error('Seleccioná al menos un canal');
      }
      await api(`/admin/content/${selectedId}`, {
        method: 'PATCH',
        body: JSON.stringify({
          caption: editCaption,
          headline: editHeadline,
          cta: editCta,
          hashtags: editHashtags.split(/[\s,]+/).filter(Boolean),
          status: 'READY',
        }),
      });
      return api<GeneratedContent>(`/admin/content/${selectedId}/publish`, {
        method: 'POST',
        body: JSON.stringify({ channels }),
      });
    },
    onSuccess: async (data) => {
      syncEditors(data);
      await queryClient.invalidateQueries({ queryKey: ['content-list'] });
      await queryClient.invalidateQueries({ queryKey: ['content-summary'] });
      await queryClient.invalidateQueries({ queryKey: ['content', data.id] });
    },
  });

  function toggleChannel(value: string) {
    setChannels((prev) =>
      prev.includes(value)
        ? prev.filter((c) => c !== value)
        : [...prev, value],
    );
  }

  function togglePublishChannel(value: string) {
    setPublishChannels((prev) =>
      prev.includes(value)
        ? prev.filter((c) => c !== value)
        : [...prev, value],
    );
  }

  const saveAutoConfig = useMutation({
    mutationFn: () =>
      api<SocialContentConfig>('/admin/content/config', {
        method: 'PATCH',
        body: JSON.stringify({
          autoGenerateEnabled: autoEnabled,
          autoGenerateDaysOfWeek: autoDays,
          autoGenerateTime: autoTime,
          autoGenerateChannels: autoChannels,
          autoGenerateObjective: autoObjective,
          notifyWhatsAppPhone,
          notifyEmail,
          preferredVideoProvider: preferredVideoProvider || null,
          preferredVideoModel: preferredVideoModel || null,
        }),
      }),
    onSuccess: async () => {
      setAutoDirty(false);
      await queryClient.invalidateQueries({ queryKey: ['content-config'] });
    },
  });

  function toggleAutoDay(day: number) {
    setAutoDirty(true);
    setAutoDays((prev) => {
      if (prev.includes(day)) {
        if (prev.length <= 1) return prev;
        return prev.filter((d) => d !== day);
      }
      return [...prev, day].sort((a, b) => a - b);
    });
  }

  function toggleAutoChannel(value: string) {
    setAutoDirty(true);
    setAutoChannels((prev) =>
      prev.includes(value)
        ? prev.filter((c) => c !== value)
        : [...prev, value],
    );
  }

  const services = servicesQuery.data ?? [];
  const hasBranding = Boolean(business.data?.brandingConfig);
  const generating =
    generate.isPending ||
    autoEdit.isPending ||
    detail?.status === 'GENERATING' ||
    detail?.status === 'PUBLISHING' ||
    detail?.autoEditStatus === 'PROCESSING' ||
    publish.isPending;
  const isGeneratingPiece =
    generate.isPending || detail?.status === 'GENERATING';
  const canPublish =
    Boolean(selectedId) &&
    Boolean(detail?.assets?.length) &&
    publishChannels.length > 0 &&
    !['GENERATING', 'PUBLISHING'].includes(detail?.status ?? '') &&
    detail?.autoEditStatus !== 'PROCESSING' &&
    !publish.isPending &&
    !autoEdit.isPending;
  const canAutoEdit =
    Boolean(selectedId) &&
    detail !== null &&
    detail !== undefined &&
    isVideoContent(detail) &&
    Boolean(
      detail.assets?.some(
        (asset) => (asset.type ?? 'IMAGE').toUpperCase() === 'VIDEO',
      ),
    ) &&
    !['GENERATING', 'PUBLISHING'].includes(detail.status) &&
    detail.autoEditStatus !== 'PROCESSING' &&
    !autoEdit.isPending &&
    !generate.isPending;
  const previewItems = (list.data ?? []).filter(
    (item) =>
      Boolean(item.assets?.length) ||
      item.status === 'GENERATING' ||
      item.status === 'PUBLISHING',
  );
  const imageItems = previewItems.filter(isImageContent);
  const videoItems = previewItems.filter(isVideoContent);

  if (selectedId) {
    const selectedItem = (list.data ?? []).find((item) => item.id === selectedId);
    if (selectedItem) {
      const matchesTab =
        mediaKind === 'video'
          ? isVideoContent(selectedItem)
          : isImageContent(selectedItem);
      if (!matchesTab) setSelectedId(null);
    }
  }

  function renderMediaToggle() {
    return (
      <div
        className="inline-flex rounded-xl border border-line bg-panel p-1 gap-1"
        role="tablist"
        aria-label="Tipo de contenido"
      >
        <button
          type="button"
          role="tab"
          aria-selected={mediaKind === 'image'}
          onClick={() => {
            setMediaKind('image');
            setChannels(['INSTAGRAM_FEED', 'INSTAGRAM_STORY']);
          }}
          className={`inline-flex items-center gap-2 rounded-lg px-4 py-2.5 text-sm min-h-10 cursor-pointer transition ${
            mediaKind === 'image'
              ? 'bg-accent text-white'
              : 'text-muted hover:text-text hover:bg-panel-2'
          }`}
        >
          Imagen
        </button>
        <button
          type="button"
          role="tab"
          aria-selected={mediaKind === 'video'}
          onClick={() => {
            setMediaKind('video');
            setChannels(['INSTAGRAM_REEL', 'INSTAGRAM_STORY', 'WHATSAPP_STATUS']);
          }}
          className={`inline-flex items-center gap-2 rounded-lg px-4 py-2.5 text-sm min-h-10 cursor-pointer transition ${
            mediaKind === 'video'
              ? 'bg-accent text-white'
              : 'text-muted hover:text-text hover:bg-panel-2'
          }`}
        >
          Video
        </button>
      </div>
    );
  }

  function renderGallery(
    items: GeneratedContent[],
    emptyLabel: string,
  ) {
    return (
      <section className="space-y-3">
        <div className="flex items-end justify-between gap-2">
          <h3 className="font-medium">
            {mediaKind === 'image' ? 'Imágenes generadas' : 'Videos generados'}
          </h3>
          <p className="text-xs text-muted tabular-nums">
            {items.length} {items.length === 1 ? 'pieza' : 'piezas'}
          </p>
        </div>
        {list.isLoading ? (
          <p className="text-sm text-muted">Cargando…</p>
        ) : !items.length ? (
          <div className="panel rounded-2xl p-6 space-y-3">
            <p className="text-sm text-muted">{emptyLabel}</p>
            <button
              type="button"
              onClick={() => setWorkspace('create')}
              className="rounded-lg bg-accent text-white px-3 py-2.5 text-sm min-h-10 cursor-pointer"
            >
              Ir a Crear
            </button>
          </div>
        ) : (
          <div className="grid gap-3 grid-cols-2 lg:grid-cols-3">
            {items.map((item) => {
              const thumbAsset = previewThumb(item);
              const thumb = thumbAsset?.storageUrl;
              const thumbVideo = isVideoContent(item);
              const active = item.id === selectedId;
              return (
                <div
                  key={item.id}
                  className={`panel rounded-2xl overflow-hidden border transition ${
                    active
                      ? 'border-accent ring-1 ring-accent/40'
                      : 'border-transparent'
                  }`}
                >
                  <button
                    type="button"
                    onClick={() => openContent(item)}
                    className="block w-full text-left"
                  >
                    <div className="aspect-[4/3] bg-panel-2 relative">
                      {item.status === 'GENERATING' ? (
                        <div className="absolute inset-0 z-10 grid place-items-center bg-panel/80">
                          <BusySpinner className="h-6 w-6" />
                        </div>
                      ) : null}
                      {thumb && thumbVideo ? (
                        <video
                          src={thumb}
                          className="w-full h-full object-cover pointer-events-none"
                          muted
                          playsInline
                          preload="metadata"
                        />
                      ) : thumb ? (
                        // eslint-disable-next-line @next/next/no-img-element
                        <img
                          src={thumb}
                          alt=""
                          className="w-full h-full object-cover"
                        />
                      ) : (
                        <div className="h-full flex items-center justify-center text-xs text-muted">
                          Generando…
                        </div>
                      )}
                    </div>
                  </button>
                  <button
                    type="button"
                    onClick={() => openContent(item)}
                    className="w-full text-left p-3 space-y-1"
                  >
                    <div className="flex items-center justify-between gap-2">
                      <p className="text-sm font-medium truncate">
                        {item.headline || item.topic || 'Sin título'}
                      </p>
                      <span
                        className={`shrink-0 text-[10px] font-medium px-1.5 py-0.5 rounded-full ${statusClass(item.status)}`}
                      >
                        {STATUS_LABEL[item.status] ?? item.status}
                      </span>
                    </div>
                    <p className="text-xs text-muted line-clamp-2">
                      {item.caption || '—'}
                    </p>
                  </button>
                </div>
              );
            })}
          </div>
        )}
      </section>
    );
  }

  return (
    <div className="space-y-8 max-w-6xl">
      <header className="flex flex-wrap items-end justify-between gap-4">
        <div className="space-y-2">
          <h2 className="text-2xl font-semibold tracking-tight">Contenido</h2>
          <p className="text-sm text-muted">
            Generá, revisá y publicá en WhatsApp, Instagram y TikTok.
            {summary.data ? (
              <span className="text-muted/80">
                {' '}
                {summary.data.generatedThisMonth} este mes
                {summary.data.drafts
                  ? ` · ${summary.data.drafts} sin publicar`
                  : ''}
              </span>
            ) : null}
          </p>
        </div>
        <Link
          href="/personalization"
          className="rounded-lg border border-line bg-panel px-3 py-2.5 text-sm min-h-10 inline-flex items-center"
        >
          {hasBranding ? 'Editar marca' : 'Configurar marca'}
        </Link>
      </header>

      <nav
        className="flex flex-wrap gap-1 border-b border-line"
        aria-label="Secciones de contenido"
      >
        {(
          [
            ['create', 'Crear'],
            ['library', 'Piezas'],
            ['guidelines', 'Lineamientos'],
            ['schedule', 'Programación'],
          ] as const
        ).map(([id, label]) => (
          <button
            key={id}
            type="button"
            onClick={() => setWorkspace(id)}
            className={`px-4 py-2.5 text-sm font-medium border-b-2 -mb-px min-h-11 cursor-pointer ${
              workspace === id
                ? 'border-accent text-text'
                : 'border-transparent text-muted hover:text-text'
            }`}
          >
            {label}
          </button>
        ))}
      </nav>

      {workspace === 'create' ? (
      <div className="space-y-6 max-w-xl">
        {renderMediaToggle()}
        <section className="panel rounded-2xl p-6 space-y-5">
          <h3 className="font-medium">
            {mediaKind === 'video' ? 'Nuevo video' : 'Nueva imagen'}
          </h3>
          {mediaKind === 'video' ? (
            <p className="text-sm text-muted">
              El video puede tardar unos minutos.
            </p>
          ) : null}
          {!hasBranding ? (
            <p className="text-sm text-amber-700 bg-amber-500/10 rounded-lg px-3 py-2">
              Tip: configurá la pestaña Marca en Personalización para mejores
              resultados.
            </p>
          ) : null}

          <label className="block space-y-1 text-sm">
            <span className="text-muted">Objetivo</span>
            <select
              className="w-full rounded-lg border border-line bg-panel px-3 py-2"
              value={objective}
              onChange={(e) => setObjective(e.target.value)}
            >
              {OBJECTIVES.map((o) => (
                <option key={o.value} value={o.value}>
                  {o.label}
                </option>
              ))}
            </select>
          </label>

          <label className="block space-y-1 text-sm">
            <span className="text-muted">Tipo de contenido</span>
            <select
              className="w-full rounded-lg border border-line bg-panel px-3 py-2"
              value={contentStyle}
              onChange={(e) => setContentStyle(e.target.value)}
            >
              {CONTENT_STYLES.map((style) => (
                <option key={style.value} value={style.value}>
                  {style.label}
                </option>
              ))}
            </select>
            <span className="block text-xs text-muted">
              La IA usa este enfoque junto a los lineamientos del negocio. Con
              “Detectar”, elige Educativo, Comedia o Venta según el brief.
            </span>
          </label>

          <div className="space-y-2 text-sm">
            <span className="text-muted">Canales</span>
            <div className="flex flex-wrap gap-2">
              {(mediaKind === 'video' ? VIDEO_CHANNELS : CHANNELS).map((ch) => {
                const on = channels.includes(ch.value);
                return (
                  <button
                    key={ch.value}
                    type="button"
                    onClick={() => toggleChannel(ch.value)}
                    className={`rounded-lg px-3 py-2 min-h-10 border text-sm cursor-pointer ${
                      on
                        ? 'border-accent bg-accent text-white'
                        : 'border-line text-muted'
                    }`}
                  >
                    {ch.label}
                  </button>
                );
              })}
            </div>
            {channels.some((c) => c.startsWith('INSTAGRAM')) &&
            !igPublishConnected ? (
              <p className="text-xs text-amber-800">
                Para publicar en Instagram conectá{' '}
                <Link href="/integrations" className="underline">
                  Instagram
                </Link>
                .
              </p>
            ) : null}
            {channels.some((c) => c.startsWith('FACEBOOK')) &&
            !facebookConnected ? (
              <p className="text-xs text-amber-800">
                Para publicar en Facebook conectá la Página en{' '}
                <Link href="/integrations" className="underline">
                  Integraciones
                </Link>
                .
              </p>
            ) : null}
            {channels.includes('TIKTOK') && !tiktokConnected ? (
              <p className="text-xs text-amber-800">
                Para publicar en TikTok conectá la cuenta en{' '}
                <Link href="/integrations" className="underline">
                  Integraciones
                </Link>
                .
              </p>
            ) : null}
          </div>

          {mediaKind === 'video' ? (
            <div className="space-y-2 text-sm">
              <span className="text-muted">Duración</span>
              <div className="flex flex-wrap gap-2">
                {VIDEO_DURATIONS.map((seconds) => {
                  const on = videoDuration === seconds;
                  return (
                    <button
                      key={seconds}
                      type="button"
                      onClick={() => setVideoDuration(seconds)}
                      className={`rounded-lg px-3 py-2 min-h-10 border text-sm cursor-pointer ${
                        on
                          ? 'border-accent bg-accent text-white'
                          : 'border-line text-muted'
                      }`}
                    >
                      {seconds}s
                    </button>
                  );
                })}
              </div>
            </div>
          ) : null}

          {mediaKind === 'video' ? (
            <>
              <div className="space-y-2 text-sm">
                <span className="text-muted">Audio / Voz</span>
                <div className="flex flex-wrap gap-2">
                  <label className={`flex items-center gap-2 rounded-lg border px-3 py-2 cursor-pointer ${videoGenerateAudio ? 'border-accent bg-accent/10' : 'border-line'}`}>
                    <input
                      type="radio"
                      name="videoGenerateAudio"
                      checked={videoGenerateAudio}
                      onChange={() => setVideoGenerateAudio(true)}
                    />
                    <span className="text-sm">Generar voz con Seedance</span>
                  </label>
                  <label className={`flex items-center gap-2 rounded-lg border px-3 py-2 cursor-pointer ${!videoGenerateAudio ? 'border-accent bg-accent/10' : 'border-line'}`}>
                    <input
                      type="radio"
                      name="videoGenerateAudio"
                      checked={!videoGenerateAudio}
                      onChange={() => setVideoGenerateAudio(false)}
                    />
                    <span className="text-sm">Generar video sin voz</span>
                  </label>
                </div>
                <p className="text-xs text-muted">
                  {videoGenerateAudio
                    ? 'Seedance genera video + audio. Podés editar la voz después con ElevenLabs.'
                    : 'Solo video, sin audio. Podés agregar voz con ElevenLabs después.'}
                </p>
              </div>
              <div className="space-y-3 text-sm rounded-xl border border-line/60 bg-panel-2/40 p-3">
                <div className="grid gap-3 sm:grid-cols-2">
                  <label className="block space-y-1">
                    <span className="text-muted">Provider (opcional)</span>
                    <select
                      className="w-full rounded-lg border border-line bg-panel px-3 py-2"
                      value={videoProvider}
                      onChange={(e) => setVideoProvider(e.target.value)}
                    >
                      <option value="">Por defecto (negocio / env)</option>
                      <option value="kie">kie.ai</option>
                      <option value="fal">fal.ai</option>
                      <option value="veo">Veo (Google)</option>
                    </select>
                  </label>
                  <label className="block space-y-1">
                    <span className="text-muted">Modelo (opcional)</span>
                    <input
                      className="w-full rounded-lg border border-line bg-panel px-3 py-2"
                      value={videoModel}
                      onChange={(e) => setVideoModel(e.target.value)}
                      placeholder="bytedance/seedance-1.5-pro"
                    />
                  </label>
                </div>
                <p className="text-xs text-muted">
                  Escribí el modelo y cambialo al momento. Vacío usa el configurado por negocio o{' '}
                  <code className="mono text-[11px]">KIE_VIDEO_MODEL</code> del .env. Ej:{' '}
                  <code className="mono text-[11px]">bytedance/seedance-1.5-pro</code>,{' '}
                  <code className="mono text-[11px]">fal-ai/kling-video/v1/standard/text-to-video</code>,{' '}
                  <code className="mono text-[11px]">veo-3.1-lite-generate-preview</code>
                </p>
              </div>
            </>
          ) : null}

          <label className="block space-y-1 text-sm">
            <span className="text-muted">Servicio (opcional)</span>
            <select
              className="w-full rounded-lg border border-line bg-panel px-3 py-2"
              value={serviceId}
              onChange={(e) => setServiceId(e.target.value)}
              disabled={servicesQuery.isLoading || services.length === 0}
            >
              <option value="">
                {servicesQuery.isLoading
                  ? 'Cargando servicios…'
                  : services.length === 0
                    ? 'No hay servicios cargados'
                    : 'Sin servicio específico'}
              </option>
              {services.map((s) => (
                <option key={s.id} value={s.id}>
                  {s.name}
                </option>
              ))}
            </select>
            {!servicesQuery.isLoading && services.length === 0 ? (
              <p className="text-xs text-muted">
                Cargá servicios en Personalización para poder asociarlos al
                contenido.
              </p>
            ) : null}
          </label>

          <div className="space-y-1 text-sm">
            <div className="flex items-center justify-between gap-2">
              <span className="text-muted">Instrucciones</span>
              <button
                type="button"
                disabled={generating || suggestBrief.isPending}
                onClick={() => suggestBrief.mutate()}
                className="inline-flex items-center gap-1.5 rounded-lg border border-line bg-panel-2 px-2.5 py-1.5 text-xs font-medium text-text hover:border-accent/50 hover:bg-accent/10 disabled:opacity-60"
              >
                <svg
                  viewBox="0 0 16 16"
                  className="h-3.5 w-3.5 text-accent"
                  aria-hidden
                >
                  <path
                    fill="currentColor"
                    d="M8 1.2 8.9 5 12.8 6 8.9 7l-.9 3.8L7.1 7 3.2 6 7.1 5 8 1.2Zm5.2 8.1.5 2.1 2.1.5-2.1.5-.5 2.1-.5-2.1-2.1-.5 2.1-.5.5-2.1ZM2.6 9.4l.4 1.5 1.5.4-1.5.4-.4 1.5-.4-1.5-1.5-.4 1.5-.4.4-1.5Z"
                  />
                </svg>
                {suggestBrief.isPending
                  ? 'Armando guion…'
                  : 'Generación de IA'}
              </button>
            </div>
            <textarea
              className="w-full min-h-36 rounded-lg border border-line bg-panel px-3 py-2"
              value={instructions}
              onChange={(e) => {
                setInstructions(e.target.value);
                if (suggestBrief.isError) suggestBrief.reset();
              }}
              placeholder={
                mediaKind === 'video'
                  ? 'O usá Generación de IA para armar un guion (inicio, escena y llamado a la acción)…'
                  : 'Ej. Promover manicura gel con 15% off esta semana…'
              }
              disabled={suggestBrief.isPending}
            />
            <p className="text-xs text-muted">
              {mediaKind === 'video'
                ? 'La IA arma un guion con el negocio, el tipo de contenido y tus lineamientos. Después podés editarlo y generar el video.'
                : 'La IA propone un brief con el negocio, el tipo de contenido y tus lineamientos. Después podés editarlo.'}
            </p>
            {suggestBrief.isError ? (
              <p className="text-sm text-red-600">
                {apiErrorMessage(
                  suggestBrief.error,
                  'No se pudo armar el guion',
                )}
              </p>
            ) : null}
          </div>

          <div className="space-y-2 text-sm">
            <div className="flex items-center justify-between gap-2">
              <span className="text-muted">
                Imágenes de referencia (opcional, máx. 4)
              </span>
              {references.length > 0 ? (
                <button
                  type="button"
                  className="text-xs text-muted hover:text-text"
                  onClick={() =>
                    setReferences((prev) => {
                      for (const ref of prev) {
                        if (ref.local) URL.revokeObjectURL(ref.url);
                      }
                      return [];
                    })
                  }
                >
                  Quitar todas
                </button>
              ) : null}
            </div>
            <p className="text-xs text-muted">
              Producto, local o estilo (opcional).
            </p>
            <input
              type="file"
              accept="image/*"
              multiple
              className="block w-full text-sm text-muted file:mr-3 file:rounded-lg file:border-0 file:bg-panel-2 file:px-3 file:py-2 file:text-sm file:text-text"
              onChange={(e) => {
                addReferenceFiles(e.target.files);
                e.target.value = '';
              }}
            />
            {references.length > 0 ? (
              <div className="grid grid-cols-4 gap-2">
                {references.map((ref) => (
                  <div
                    key={ref.id}
                    className="relative aspect-square rounded-lg overflow-hidden border border-line bg-panel-2"
                  >
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img
                      src={ref.url}
                      alt=""
                      className="w-full h-full object-cover"
                    />
                    <button
                      type="button"
                      onClick={() => removeReference(ref.id)}
                      className="absolute top-1 right-1 rounded bg-black/60 text-white text-[10px] px-1.5 py-0.5"
                    >
                      ✕
                    </button>
                  </div>
                ))}
              </div>
            ) : null}
          </div>

          <button
            type="button"
            disabled={generating || suggestBrief.isPending || channels.length === 0}
            onClick={() =>
              generate.mutate({
                objective,
                channels,
                userInstructions: instructions.trim() || undefined,
                serviceId: serviceId || undefined,
                contentStyle,
              })
            }
            className="w-full rounded-lg bg-accent text-white px-3 py-2.5 text-sm font-medium disabled:opacity-60 min-h-10"
          >
            {generate.isPending
              ? 'Generando…'
              : mediaKind === 'video'
                ? 'Generar video'
                : 'Generar imagen'}
          </button>
          {generate.isError ? (
            <p className="text-sm text-red-600">
              {(generate.error as Error)?.message ||
                'No se pudo generar el contenido'}
            </p>
          ) : null}
        </section>
      </div>
      ) : null}

      {workspace === 'guidelines' ? <ContentKnowledgePanel /> : null}

      {workspace === 'library' ? (
      <div className="space-y-6">
        {renderMediaToggle()}
        <div className="grid gap-8 lg:grid-cols-[minmax(0,1fr)_minmax(0,1.05fr)]">
        <section className="panel rounded-2xl p-6 space-y-5 min-h-[28rem] order-1 lg:order-2">
          {!selectedId || !detail ? (
            <div className="h-full flex items-center justify-center text-sm text-muted py-16 px-6 text-center">
              Elegí una pieza de la lista para editarla o publicarla.
            </div>
          ) : (
            <>
              <div className="flex flex-wrap items-center justify-between gap-2">
                <div>
                  <h3 className="font-medium">
                    {detail.headline || detail.topic || 'Sin título'}
                  </h3>
                  <p className="text-xs text-muted mt-0.5">
                    {OBJECTIVES.find((o) => o.value === detail.objective)
                      ?.label ?? detail.objective}
                  </p>
                </div>
                <div className="flex flex-wrap items-center gap-2">
                  <span
                    className={`inline-flex items-center gap-1.5 text-[11px] font-medium px-2 py-0.5 rounded-full ${statusClass(isGeneratingPiece ? 'GENERATING' : detail.status)}`}
                  >
                    {isGeneratingPiece ? (
                      <>
                        <BusySpinner className="h-3 w-3 border-accent/30 border-t-accent" />
                        {detail.assets?.length ? 'Regenerando…' : 'Generando…'}
                      </>
                    ) : (
                      (STATUS_LABEL[detail.status] ?? detail.status)
                    )}
                  </span>
                  {detail.autoEditStatus ? (
                    <span
                      className={`text-[11px] font-medium px-2 py-0.5 rounded-full ${autoEditClass(detail.autoEditStatus)}`}
                    >
                      {AUTO_EDIT_LABEL[detail.autoEditStatus] ??
                        detail.autoEditStatus}
                    </span>
                  ) : null}
                </div>
              </div>

              {detail.autoEditError ? (
                <p className="text-sm text-amber-800 bg-amber-500/10 rounded-lg px-3 py-2">
                  No se pudo aplicar la edición automática. Podés publicar el
                  video original o reintentar.
                </p>
              ) : null}

              {isGeneratingPiece ? (
                <div
                  className="flex items-start gap-3 rounded-xl border border-accent/25 bg-accent-soft px-4 py-3"
                  role="status"
                  aria-live="polite"
                >
                  <BusySpinner className="h-5 w-5 mt-0.5" />
                  <div className="space-y-0.5 min-w-0">
                    <p className="text-sm font-medium text-text">
                      {detail.assets?.length
                        ? 'Estamos armando una versión nueva'
                        : mediaKind === 'video'
                          ? 'Estamos generando el video'
                          : 'Estamos generando la imagen'}
                    </p>
                    <p className="text-sm text-muted">
                      {mediaKind === 'video'
                        ? 'Puede tardar unos minutos. Esta vista se actualiza sola cuando esté lista.'
                        : 'En unos segundos aparece acá la pieza nueva.'}
                    </p>
                  </div>
                </div>
              ) : null}

              {detail.autoEditStatus === 'PROCESSING' || autoEdit.isPending ? (
                <p className="text-sm text-muted">
                  Aplicando la edición al video…
                </p>
              ) : null}

              <div className="relative grid gap-3 sm:grid-cols-2">
                {isGeneratingPiece && detail.assets?.length ? (
                  <div className="absolute inset-0 z-10 rounded-xl bg-panel/70 backdrop-blur-[2px] grid place-items-center">
                    <div className="flex flex-col items-center gap-2 text-center px-4">
                      <BusySpinner className="h-8 w-8" />
                      <p className="text-sm font-medium">Regenerando la pieza…</p>
                    </div>
                  </div>
                ) : null}
                {(detail.assets?.length ? [...detail.assets].sort((a, b) => {
                  if (a.role === 'EDITED' && b.role !== 'EDITED') return -1;
                  if (b.role === 'EDITED' && a.role !== 'EDITED') return 1;
                  return 0;
                }) : []).map((asset) => {
                  const isVideo = (asset.type ?? 'IMAGE').toUpperCase() === 'VIDEO';
                  return (
                  <figure
                    key={asset.id}
                    className="rounded-xl overflow-hidden border border-line bg-panel-2"
                  >
                    {isVideo ? (
                      <button
                        type="button"
                        className="relative block w-full cursor-zoom-in group"
                        onClick={() =>
                          setLightbox({
                            url: asset.storageUrl,
                            video: true,
                            label: assetRoleLabel(asset, true),
                          })
                        }
                      >
                        <video
                          key={asset.storageUrl}
                          src={asset.storageUrl}
                          className="w-full object-cover max-h-72 pointer-events-none"
                          muted
                          playsInline
                          preload="metadata"
                        />
                        <span className="absolute inset-0 grid place-items-center bg-black/25 group-hover:bg-black/35 transition">
                          <span className="inline-flex h-11 w-11 items-center justify-center rounded-full bg-white/90 text-text shadow-sm">
                            <svg
                              viewBox="0 0 20 20"
                              className="h-4 w-4 ml-0.5"
                              aria-hidden
                            >
                              <path fill="currentColor" d="M6.5 4.5v11l9-5.5-9-5.5Z" />
                            </svg>
                          </span>
                        </span>
                      </button>
                    ) : (
                      <button
                        type="button"
                        className="block w-full cursor-zoom-in"
                        onClick={() =>
                          setLightbox({
                            url: asset.storageUrl,
                            video: false,
                            label: asset.format,
                          })
                        }
                      >
                        {/* eslint-disable-next-line @next/next/no-img-element */}
                        <img
                          src={asset.storageUrl}
                          alt={asset.format}
                          className="w-full object-cover max-h-72"
                        />
                      </button>
                    )}
                    <figcaption className="px-2 py-1.5 text-[11px] text-muted">
                      {assetRoleLabel(asset, isVideo)}
                    </figcaption>
                  </figure>
                  );
                })}
                  {!detail.assets?.length && isGeneratingPiece ? (
                  <div className="sm:col-span-2 rounded-xl border border-dashed border-line bg-panel-2 min-h-48 grid place-items-center px-6 py-10">
                    <div className="flex flex-col items-center gap-2 text-center">
                      <BusySpinner className="h-8 w-8" />
                      <p className="text-sm font-medium">
                        Generando {mediaKind === 'video' ? 'video' : 'imagen'}…
                      </p>
                    </div>
                  </div>
                ) : null}
              </div>

              {ELEVENLABS_ENABLED && detail && isVideoContent(detail) ? (
                <VideoVoiceEditor contentId={detail.id} detail={detail} />
              ) : null}

              <nav
                className="flex gap-1 border-b border-line"
                aria-label="Acciones de la pieza"
              >
                {(
                  [
                    ['edit', 'Editar'],
                    ['publish', 'Publicar'],
                  ] as const
                ).map(([id, label]) => (
                  <button
                    key={id}
                    type="button"
                    onClick={() => setPieceTab(id)}
                    className={`px-3 py-2 text-sm font-medium border-b-2 -mb-px min-h-10 cursor-pointer ${
                      pieceTab === id
                        ? 'border-accent text-text'
                        : 'border-transparent text-muted hover:text-text'
                    }`}
                  >
                    {label}
                  </button>
                ))}
              </nav>

              {pieceTab === 'edit' ? (
              <div className="space-y-5">
              <label className="block space-y-1 text-sm">
                <span className="text-muted">Título</span>
                <input
                  className="w-full rounded-lg border border-line bg-panel px-3 py-2"
                  value={editHeadline}
                  onChange={(e) => setEditHeadline(e.target.value)}
                />
              </label>
              <label className="block space-y-1 text-sm">
                <span className="text-muted">Caption</span>
                <textarea
                  className="w-full min-h-28 rounded-lg border border-line bg-panel px-3 py-2"
                  value={editCaption}
                  onChange={(e) => setEditCaption(e.target.value)}
                />
              </label>
              <label className="block space-y-1 text-sm">
                <span className="text-muted">CTA</span>
                <input
                  className="w-full rounded-lg border border-line bg-panel px-3 py-2"
                  value={editCta}
                  onChange={(e) => setEditCta(e.target.value)}
                />
              </label>
              <label className="block space-y-1 text-sm">
                <span className="text-muted">Hashtags</span>
                <input
                  className="w-full rounded-lg border border-line bg-panel px-3 py-2"
                  value={editHashtags}
                  onChange={(e) => setEditHashtags(e.target.value)}
                  placeholder="#parrilla #gastronomia"
                />
              </label>
              {detail.hook ? (
                <p className="text-xs text-muted">
                  Inicio del video: {detail.hook}
                </p>
              ) : null}

              <div className="flex flex-wrap gap-2">
                <button
                  type="button"
                  disabled={saveDraft.isPending}
                  onClick={() => saveDraft.mutate()}
                  className="rounded-lg border border-line bg-panel px-3 py-2.5 text-sm min-h-10 disabled:opacity-60 cursor-pointer"
                >
                  {saveDraft.isPending ? 'Guardando…' : 'Guardar'}
                </button>
                <button
                  type="button"
                  disabled={generating}
                  onClick={() =>
                    generate.mutate({
                      objective: detail.objective,
                      channels: detail.channels,
                      userInstructions: instructions.trim() || undefined,
                      serviceId: detail.service?.id,
                      contentId: detail.id,
                    })
                  }
                  className={`inline-flex items-center gap-2 rounded-lg px-3 py-2.5 text-sm min-h-10 disabled:opacity-80 cursor-pointer ${
                    isGeneratingPiece
                      ? 'bg-accent text-white'
                      : 'border border-line bg-panel'
                  }`}
                >
                  {isGeneratingPiece ? (
                    <>
                      <BusySpinner className="h-3.5 w-3.5 border-white/35 border-t-white" />
                      Regenerando…
                    </>
                  ) : (
                    'Regenerar'
                  )}
                </button>
                {isVideoContent(detail) ? (
                  <button
                    type="button"
                    disabled={!canAutoEdit}
                    onClick={() => autoEdit.mutate()}
                    className="rounded-lg border border-line bg-panel px-3 py-2.5 text-sm min-h-10 disabled:opacity-60 cursor-pointer"
                  >
                    {autoEdit.isPending || detail.autoEditStatus === 'PROCESSING'
                      ? 'Editando…'
                      : detail.autoEditStatus === 'COMPLETED'
                        ? 'Reaplicar edición'
                        : 'Aplicar edición'}
                  </button>
                ) : null}
                <button
                  type="button"
                  disabled={remove.isPending}
                  onClick={() => {
                    if (confirm('¿Eliminar este contenido?')) {
                      remove.mutate(detail.id);
                    }
                  }}
                  className="rounded-lg border border-line bg-panel px-3 py-2.5 text-sm min-h-10 text-red-600 cursor-pointer"
                >
                  Eliminar
                </button>
              </div>
              {autoEdit.isError ? (
                <p className="text-sm text-red-600">
                  No se pudo aplicar la edición al video.
                </p>
              ) : null}
              </div>
              ) : (
              <div className="space-y-4">
                <p className="text-sm text-muted">
                  Elegí dónde querés publicarlo.
                </p>
                <div className="flex flex-wrap gap-2">
                  {(mediaKind === 'video' ? VIDEO_CHANNELS : CHANNELS).map((ch) => {
                    const on = publishChannels.includes(ch.value);
                    return (
                      <button
                        key={ch.value}
                        type="button"
                        onClick={() => togglePublishChannel(ch.value)}
                        className={`rounded-lg px-3 py-2 min-h-10 border text-sm cursor-pointer ${
                          on
                            ? 'border-accent bg-accent text-white'
                            : 'border-line text-muted'
                        }`}
                      >
                        {ch.label}
                      </button>
                    );
                  })}
                </div>
                {publishChannels.some((c) => c.startsWith('FACEBOOK')) &&
                !facebookConnected ? (
                  <p className="text-xs text-amber-800">
                    Para publicar en Facebook conectá la Página en{' '}
                    <Link href="/integrations" className="underline">
                      Integraciones
                    </Link>
                    .
                  </p>
                ) : null}
                {!detail.assets?.length ? (
                  <p className="text-sm text-amber-700">
                    Este borrador todavía no tiene media. Esperá a que termine
                    la generación o regeneralo antes de publicar.
                  </p>
                ) : null}
                <button
                  type="button"
                  disabled={!canPublish}
                  onClick={() => {
                    const labels = publishChannels
                      .map((c) => CHANNEL_LABEL[c] ?? c)
                      .join(', ');
                    if (confirm(`¿Publicar ahora en: ${labels}?`)) {
                      publish.mutate();
                    }
                  }}
                  className="w-full rounded-lg bg-accent text-white px-3 py-3 text-sm font-semibold disabled:opacity-60 min-h-11 cursor-pointer"
                >
                  {publish.isPending || detail.status === 'PUBLISHING'
                    ? 'Publicando…'
                    : 'Publicar'}
                </button>
                {publish.isError ? (
                  <p className="text-sm text-red-600">
                    {(publish.error as Error)?.message ||
                      'No se pudo publicar el contenido'}
                  </p>
                ) : null}
              </div>
              )}
            </>
          )}
        </section>
        <div className="order-2 lg:order-1 min-w-0">
        {renderGallery(
          mediaKind === 'video' ? videoItems : imageItems,
          mediaKind === 'video'
            ? 'Todavía no hay videos. Creá uno en la solapa Crear.'
            : 'Todavía no hay imágenes. Creá una en la solapa Crear.',
        )}
        </div>
        </div>
      </div>
      ) : null}

      {workspace === 'schedule' ? (
      <section className="panel rounded-2xl p-6 space-y-6">
        <div className="flex flex-wrap items-start justify-between gap-3">
          <div>
            <h3 className="font-medium">Generación automática</h3>
            <p className="text-sm text-muted mt-1">
              Elegí los días y la hora. Preparamos borradores solos para que
              los revises y publiques.
            </p>
          </div>
          <label className="inline-flex items-center gap-2 text-sm min-h-10 cursor-pointer">
            <input
              type="checkbox"
              className="h-4 w-4"
              checked={autoEnabled}
              onChange={(e) => {
                setAutoDirty(true);
                setAutoEnabled(e.target.checked);
              }}
            />
            Activar
          </label>
        </div>

        <div className="space-y-2">
          <div className="flex flex-wrap items-center gap-2">
            <span className="text-sm text-muted">Días</span>
            <button
              type="button"
              className="text-xs text-muted underline-offset-2 hover:underline"
              onClick={() => {
                setAutoDirty(true);
                setAutoDays([1, 2, 3, 4, 5, 6, 7]);
              }}
            >
              Todos
            </button>
            <button
              type="button"
              className="text-xs text-muted underline-offset-2 hover:underline"
              onClick={() => {
                setAutoDirty(true);
                setAutoDays([1, 2, 3, 4, 5]);
              }}
            >
              Lun–Vie
            </button>
          </div>
          <div className="flex flex-wrap gap-2">
            {WEEKDAYS.map((day) => {
              const on = autoDays.includes(day.value);
              return (
                <button
                  key={day.value}
                  type="button"
                  disabled={!autoEnabled}
                  onClick={() => toggleAutoDay(day.value)}
                  className={`rounded-lg border px-3 py-2 text-sm min-h-10 ${
                    on
                      ? 'border-accent bg-accent text-white'
                      : 'border-line text-muted'
                  } disabled:opacity-50`}
                >
                  {day.label}
                </button>
              );
            })}
          </div>
        </div>

        <div className="grid gap-4 sm:grid-cols-2">
          <label className="block space-y-1 text-sm">
            <span className="text-muted">Horario</span>
            <input
              type="time"
              disabled={!autoEnabled}
              className="w-full rounded-lg border border-line bg-panel px-3 py-2 disabled:opacity-50"
              value={autoTime}
              onChange={(e) => {
                setAutoDirty(true);
                setAutoTime(e.target.value);
              }}
            />
          </label>
          <label className="block space-y-1 text-sm">
            <span className="text-muted">Objetivo</span>
            <select
              disabled={!autoEnabled}
              className="w-full rounded-lg border border-line bg-panel px-3 py-2 disabled:opacity-50"
              value={autoObjective}
              onChange={(e) => {
                setAutoDirty(true);
                setAutoObjective(e.target.value);
              }}
            >
              {OBJECTIVES.map((item) => (
                <option key={item.value} value={item.value}>
                  {item.label}
                </option>
              ))}
            </select>
          </label>
        </div>

        <div className="space-y-2">
          <span className="text-sm text-muted">Canales</span>
          <div className="flex flex-wrap gap-2">
            {AUTO_CHANNELS.map((ch) => {
              const on = autoChannels.includes(ch.value);
              return (
                <button
                  key={ch.value}
                  type="button"
                  disabled={!autoEnabled}
                  onClick={() => toggleAutoChannel(ch.value)}
                  className={`rounded-lg border px-3 py-2 text-sm min-h-10 ${
                    on
                      ? 'border-nav-active bg-nav-active/15 text-text'
                      : 'border-line text-muted'
                  } disabled:opacity-50`}
                >
                  {ch.label}
                </button>
              );
            })}
          </div>
        </div>

        <div className="rounded-xl border border-line/80 bg-bg/40 p-4 space-y-3">
          <div>
            <p className="text-sm font-medium">Video — modelo por defecto</p>
            <p className="text-xs text-muted mt-1">
              Se usa cuando generás VIDEO sin escribir modelo arriba. Vacío usa{' '}
              <code className="mono text-[11px]">.env</code> (<code className="mono text-[11px]">KIE_VIDEO_MODEL</code> /{' '}
              <code className="mono text-[11px]">FAL_VIDEO_MODEL</code> / <code className="mono text-[11px]">VEO_VIDEO_MODEL</code>).
              Escribí y guardá para cambiarlo al momento sin redeploy.
            </p>
          </div>
          <div className="grid gap-4 sm:grid-cols-2">
            <label className="block space-y-1 text-sm">
              <span className="text-muted">Provider</span>
              <select
                className="w-full rounded-lg border border-line bg-panel px-3 py-2 disabled:opacity-50"
                value={preferredVideoProvider}
                onChange={(e) => {
                  setAutoDirty(true);
                  setPreferredVideoProvider(e.target.value);
                }}
              >
                <option value="">Por defecto (env)</option>
                <option value="kie">kie.ai</option>
                <option value="fal">fal.ai</option>
                <option value="veo">Veo (Google)</option>
              </select>
            </label>
            <label className="block space-y-1 text-sm">
              <span className="text-muted">Modelo</span>
              <input
                type="text"
                placeholder="bytedance/seedance-1.5-pro"
                className="w-full rounded-lg border border-line bg-panel px-3 py-2 disabled:opacity-50"
                value={preferredVideoModel}
                onChange={(e) => {
                  setAutoDirty(true);
                  setPreferredVideoModel(e.target.value);
                }}
              />
            </label>
          </div>
          <p className="text-xs text-muted">
            Ej: <code className="mono text-[11px]">bytedance/seedance-1.5-pro</code> (kie),{' '}
            <code className="mono text-[11px]">fal-ai/kling-video/v1/standard/text-to-video</code> (fal),{' '}
            <code className="mono text-[11px]">veo-3.1-lite-generate-preview</code> (veo). Vacío = usa .env.
          </p>
        </div>

        <div className="rounded-xl border border-line/80 bg-bg/40 p-4 space-y-3">
          <div>
            <p className="text-sm font-medium">Avisos cuando se genera</p>
            <p className="text-xs text-muted mt-1">
              Si WhatsApp está conectado, te mandamos un mensaje al número.
              Si no, usamos el email.
            </p>
          </div>
          <div className="flex flex-wrap items-center gap-2 text-xs">
            <span
              className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 ${
                waConnected
                  ? 'bg-emerald-500/15 text-emerald-800'
                  : 'bg-line/60 text-muted'
              }`}
            >
              <span
                className={`h-1.5 w-1.5 rounded-full ${
                  waConnected ? 'bg-emerald-600' : 'bg-muted'
                }`}
              />
              {waConnected ? 'WhatsApp conectado' : 'WhatsApp desconectado'}
            </span>
            {!waConnected ? (
              <Link
                href="/integrations"
                className="text-muted underline-offset-2 hover:underline"
              >
                Conectar en Integraciones
              </Link>
            ) : null}
          </div>
          <div className="grid gap-4 sm:grid-cols-2">
            <label className="block space-y-1 text-sm">
              <span className="text-muted">Número de WhatsApp</span>
              <input
                type="tel"
                inputMode="tel"
                placeholder="54911..."
                className="w-full rounded-lg border border-line bg-panel px-3 py-2 disabled:opacity-50"
                value={notifyWhatsAppPhone}
                onChange={(e) => {
                  setAutoDirty(true);
                  setNotifyWhatsAppPhone(e.target.value);
                }}
              />
              <span className="block text-xs text-muted">
                Con código de país, sin 0 ni 15. Ej. 54911...
              </span>
            </label>
            <label className="block space-y-1 text-sm">
              <span className="text-muted">Email de respaldo</span>
              <input
                type="email"
                placeholder="vos@negocio.com"
                className="w-full rounded-lg border border-line bg-panel px-3 py-2 disabled:opacity-50"
                value={notifyEmail}
                onChange={(e) => {
                  setAutoDirty(true);
                  setNotifyEmail(e.target.value);
                }}
              />
              <span className="block text-xs text-muted">
                Se usa si WhatsApp no está conectado o el envío falla.
              </span>
            </label>
          </div>
        </div>

        <div className="flex flex-wrap items-center gap-3">
          <button
            type="button"
            className="rounded-lg bg-nav-active text-white px-4 py-2.5 text-sm min-h-10 disabled:opacity-50"
            disabled={
              saveAutoConfig.isPending ||
              (autoEnabled &&
                (autoDays.length === 0 || autoChannels.length === 0))
            }
            onClick={() => saveAutoConfig.mutate()}
          >
            {saveAutoConfig.isPending ? 'Guardando…' : 'Guardar programación'}
          </button>
          {socialConfig.data?.lastAutoGenerateAt ? (
            <p className="text-xs text-muted">
              Última automática:{' '}
              {formatPubDate(socialConfig.data.lastAutoGenerateAt)}
            </p>
          ) : null}
          {saveAutoConfig.isSuccess && !autoDirty ? (
            <p className="text-xs text-emerald-700">Guardado</p>
          ) : null}
          {saveAutoConfig.isError ? (
            <p className="text-xs text-red-600">
              {(saveAutoConfig.error as Error)?.message || 'No se pudo guardar'}
            </p>
          ) : null}
        </div>
      </section>
      ) : null}
      {lightbox ? (
        <MediaLightbox media={lightbox} onClose={() => setLightbox(null)} />
      ) : null}
    </div>
  );
}

function VideoVoiceEditor({ contentId, detail }: { contentId: string; detail: GeneratedContent }) {
  const queryClient = useQueryClient();
  const [text, setText] = useState(detail.hook || detail.caption || detail.headline || '');
  const [selectedVoice, setSelectedVoice] = useState('');
  const [previewAudioUrl, setPreviewAudioUrl] = useState<string | null>(null);
  const [previewLoading, setPreviewLoading] = useState(false);

  useEffect(() => {
    setText(detail.hook || detail.caption || detail.headline || '');
  }, [detail.hook, detail.caption, detail.headline]);

  const voicesQuery = useQuery({
    queryKey: ['voices'],
    queryFn: () => api<{ voices: Array<{ voiceId: string; name: string; language?: string; gender?: string; previewUrl?: string | null; accent?: string }> }>('/admin/voices'),
  });

  const audioList = useQuery({
    queryKey: ['audio-assets', contentId],
    queryFn: () => api<Array<{ id: string; voiceId: string; voiceName?: string; text: string; status: string; storageUrl?: string; createdAt: string }>>(`/admin/content/${contentId}/audio`),
    enabled: Boolean(contentId),
  });

  const voices = voicesQuery.data?.voices ?? [];

  useEffect(() => {
    if (!selectedVoice && voices.length) setSelectedVoice(voices[0].voiceId);
  }, [voices, selectedVoice]);

  const preview = async () => {
    if (!text.trim() || !selectedVoice) return;
    setPreviewLoading(true);
    try {
      const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:3001/api'}/admin/voice/preview`, {
        method: 'POST',
        credentials: 'include',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text: text.trim(), voiceId: selectedVoice }),
      });
      if (!res.ok) throw new Error(await res.text());
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      setPreviewAudioUrl((prev) => {
        if (prev) URL.revokeObjectURL(prev);
        return url;
      });
    } catch (e) {
      alert(e instanceof Error ? e.message : 'No se pudo generar preview');
    } finally {
      setPreviewLoading(false);
    }
  };

  const generateVoice = useMutation({
    mutationFn: () =>
      api<{ id: string }>(`/admin/content/${contentId}/voice`, {
        method: 'POST',
        body: JSON.stringify({
          text: text.trim(),
          voiceId: selectedVoice,
          voiceName: voices.find((v) => v.voiceId === selectedVoice)?.name,
        }),
      }),
    onSuccess: async () => {
      await queryClient.invalidateQueries({ queryKey: ['audio-assets', contentId] });
      await queryClient.invalidateQueries({ queryKey: ['content-list'] });
      await queryClient.invalidateQueries({ queryKey: ['content', contentId] });
    },
  });

  const replaceAudio = useMutation({
    mutationFn: (audioAssetId: string) =>
      api(`/admin/content/${contentId}/replace-audio`, {
        method: 'POST',
        body: JSON.stringify({ audioAssetId }),
      }),
    onSuccess: async () => {
      await queryClient.invalidateQueries({ queryKey: ['content-list'] });
      await queryClient.invalidateQueries({ queryKey: ['content', contentId] });
      await queryClient.invalidateQueries({ queryKey: ['audio-assets', contentId] });
    },
  });

  const isVideo = isVideoContent(detail);
  const voiceProviderInfo = detail.assets?.some((a) => a.provider === 'elevenlabs') ? 'elevenlabs' : isVideo ? 'seedance' : null;

  return (
    <section className="rounded-2xl border border-line bg-panel-2/60 p-4 space-y-4">
      <div className="flex items-center justify-between gap-2">
        <h4 className="font-medium text-sm">Voz del video</h4>
        <span className="text-xs text-muted">
          {isVideo ? 'Seedance genera video + audio. Podés reemplazar solo el audio.' : '—'}
        </span>
      </div>

      <div className="text-xs text-muted">
        {voiceProviderInfo === 'seedance' ? 'Voz actual: Seedance' : voiceProviderInfo === 'elevenlabs' ? 'Voz: ElevenLabs' : 'Sin voz / original'}
        {detail.assets?.find((a) => a.role === 'COMPOSED') ? ' · versión compuesta disponible' : ''}
      </div>

      <label className="block space-y-1 text-sm">
        <span className="text-muted">Narración</span>
        <textarea
          className="w-full min-h-24 rounded-lg border border-line bg-panel px-3 py-2"
          value={text}
          onChange={(e) => setText(e.target.value)}
          placeholder="Encontrá tu próximo hogar en Villa Crespo."
          maxLength={5000}
        />
        <span className="block text-xs text-muted">{text.length}/5000</span>
      </label>

      <label className="block space-y-1 text-sm">
        <span className="text-muted">Voz ElevenLabs</span>
        <select
          className="w-full rounded-lg border border-line bg-panel px-3 py-2"
          value={selectedVoice}
          onChange={(e) => setSelectedVoice(e.target.value)}
          disabled={voicesQuery.isLoading}
        >
          {voicesQuery.isLoading ? <option>Cargando voces…</option> : null}
          {!voices.length && !voicesQuery.isLoading ? <option value="">Sin voces (configurá ELEVENLABS_API_KEY)</option> : null}
          {voices.map((v) => (
            <option key={v.voiceId} value={v.voiceId}>
              {v.name} {v.language ? `— ${v.language}` : ''} {v.gender ? `(${v.gender})` : ''} — {v.voiceId}
            </option>
          ))}
        </select>
        {voicesQuery.isError ? (
          <span className="block text-xs text-amber-700">No se pudieron cargar voces. Verificá ELEVENLABS_API_KEY en env.</span>
        ) : null}
        {voices.find((v) => v.voiceId === selectedVoice)?.previewUrl ? (
          <audio controls src={voices.find((v) => v.voiceId === selectedVoice)?.previewUrl ?? undefined} className="w-full mt-2 h-8" />
        ) : null}
      </label>

      <div className="flex flex-wrap gap-2">
        <button
          type="button"
          disabled={!text.trim() || !selectedVoice || previewLoading}
          onClick={preview}
          className="rounded-lg border border-line bg-panel px-3 py-2 text-sm disabled:opacity-50"
        >
          {previewLoading ? 'Cargando…' : '▶ Escuchar preview'}
        </button>
        <button
          type="button"
          disabled={!text.trim() || !selectedVoice || generateVoice.isPending}
          onClick={() => generateVoice.mutate()}
          className="rounded-lg bg-accent text-white px-3 py-2 text-sm disabled:opacity-50"
        >
          {generateVoice.isPending ? 'Generando…' : 'Generar nueva voz'}
        </button>
      </div>
      {previewAudioUrl ? (
        <audio controls src={previewAudioUrl} autoPlay className="w-full h-8 mt-2" />
      ) : null}
      {generateVoice.isError ? (
        <p className="text-xs text-red-600">{(generateVoice.error as Error).message}</p>
      ) : null}
      {generateVoice.isSuccess ? (
        <p className="text-xs text-emerald-700">Voz generada. Aparece abajo — podés reemplazar el audio del video.</p>
      ) : null}

      {audioList.data?.length ? (
        <div className="space-y-2">
          <p className="text-sm font-medium">Versiones de audio</p>
          <ul className="space-y-2">
            {audioList.data.map((a) => (
              <li key={a.id} className="rounded-lg border border-line bg-panel p-3 flex flex-wrap items-center justify-between gap-2">
                <div className="min-w-0">
                  <p className="text-sm font-medium truncate max-w-[320px]">{a.voiceName || a.voiceId}</p>
                  <p className="text-xs text-muted truncate max-w-[320px]">{a.text?.slice(0, 80)}</p>
                  <p className="text-[11px] text-muted">{a.status} · {new Date(a.createdAt).toLocaleString('es-AR')}</p>
                  {a.storageUrl ? <audio controls src={a.storageUrl} className="w-full mt-1 h-7" /> : null}
                </div>
                <button
                  type="button"
                  disabled={replaceAudio.isPending}
                  onClick={() => {
                    if (confirm('¿Reemplazar audio del video por esta voz? No se regenera el video, solo se compone el audio con FFmpeg.')) {
                      replaceAudio.mutate(a.id);
                    }
                  }}
                  className="rounded-lg bg-nav-active text-white px-3 py-1.5 text-xs disabled:opacity-50"
                >
                  {replaceAudio.isPending ? 'Componiendo…' : 'Reemplazar audio'}
                </button>
              </li>
            ))}
          </ul>
          {replaceAudio.isError ? <p className="text-xs text-red-600">{(replaceAudio.error as Error).message}</p> : null}
          {replaceAudio.isSuccess ? <p className="text-xs text-emerald-700">✓ Video actualizado con nueva voz (preservando original).</p> : null}
          <p className="text-xs text-muted">El video original Seedance permanece intacto. Cada composición crea un nuevo asset COMPOSED.</p>
        </div>
      ) : null}
    </section>
  );
}
