'use client';

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { api, apiForm } from '@/lib/api';

interface ContentAsset {
  id: string;
  type?: string;
  format: string;
  storageUrl: string;
  width?: number | null;
  height?: number | null;
}

interface GeneratedContent {
  id: string;
  status: string;
  objective: string;
  channels: string[];
  mediaType?: string;
  topic?: string | null;
  headline?: string | null;
  caption?: string | null;
  cta?: string | null;
  error?: string | null;
  createdAt: string;
  referenceImageUrls?: string[];
  assets: ContentAsset[];
  publications?: ContentPublication[];
  service?: { id: string; name: string } | null;
}

interface ContentPublication {
  id: string;
  channel: string;
  status: string;
  externalId?: string | null;
  error?: string | null;
  publishedAt?: string | null;
}

interface ContentSummary {
  generatedThisMonth: number;
  published: number;
  scheduled: number;
  drafts: number;
  failed: number;
  imageGenerationsThisMonth: number;
  videoGenerationsThisMonth?: number;
  estimatedCostThisMonth: number;
}

interface SocialContentConfig {
  id: string;
  autoGenerateEnabled: boolean;
  autoGenerateDaysOfWeek: number[];
  autoGenerateTime: string;
  autoGenerateChannels: string[];
  autoGenerateObjective: string;
  notifyWhatsAppPhone?: string | null;
  notifyEmail?: string | null;
  lastAutoGenerateAt?: string | null;
  defaultChannels: string[];
}

interface WhatsAppStatus {
  status: string;
}

const WEEKDAYS = [
  { value: 1, label: 'Lun' },
  { value: 2, label: 'Mar' },
  { value: 3, label: 'Mié' },
  { value: 4, label: 'Jue' },
  { value: 5, label: 'Vie' },
  { value: 6, label: 'Sáb' },
  { value: 7, label: 'Dom' },
] as const;

interface ServiceRow {
  id: string;
  name: string;
  enabled: boolean;
}

interface ReferencePreview {
  id: string;
  file?: File;
  url: string;
  local: boolean;
}

const OBJECTIVES = [
  { value: 'AUTOMATIC', label: 'Automático' },
  { value: 'SERVICE_PROMOTION', label: 'Promoción de servicio' },
  { value: 'OFFER', label: 'Oferta' },
  { value: 'TIP', label: 'Consejo / tip' },
  { value: 'INFO', label: 'Informativo' },
  { value: 'SPECIAL_DATE', label: 'Fecha especial' },
  { value: 'CUSTOM', label: 'Personalizado' },
] as const;

const CHANNELS = [
  { value: 'WHATSAPP_STATUS', label: 'WhatsApp Status' },
  { value: 'INSTAGRAM_STORY', label: 'Instagram Story' },
  { value: 'INSTAGRAM_FEED', label: 'Instagram Feed' },
] as const;

const VIDEO_CHANNELS = [
  { value: 'INSTAGRAM_REEL', label: 'Instagram Reel' },
  { value: 'INSTAGRAM_STORY', label: 'Instagram Story' },
  { value: 'WHATSAPP_STATUS', label: 'WhatsApp Status' },
] as const;

const VIDEO_DURATIONS = [5, 10, 15] as const;

const CHANNEL_LABEL: Record<string, string> = {
  WHATSAPP_STATUS: 'WhatsApp Status',
  INSTAGRAM_STORY: 'Instagram Story',
  INSTAGRAM_FEED: 'Instagram Feed',
  INSTAGRAM_REEL: 'Instagram Reel',
};

const STATUS_LABEL: Record<string, string> = {
  DRAFT: 'Borrador',
  READY: 'Listo',
  GENERATING: 'Generando…',
  PUBLISHING: 'Publicando…',
  SCHEDULED: 'Programado',
  PUBLISHED: 'Publicado',
  PARTIALLY_PUBLISHED: 'Parcial',
  FAILED: 'Error',
};

function statusClass(status: string) {
  if (
    status === 'READY' ||
    status === 'DRAFT' ||
    status === 'PUBLISHED'
  ) {
    return 'badge-success';
  }
  if (status === 'PARTIALLY_PUBLISHED') return 'bg-amber-500/15 text-amber-700';
  if (status === 'GENERATING' || status === 'PUBLISHING') return 'badge-muted';
  if (status === 'FAILED') return 'bg-red-500/15 text-red-600';
  return 'badge-muted';
}

function formatPubDate(value?: string | null) {
  if (!value) return null;
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return null;
  const dd = String(date.getDate()).padStart(2, '0');
  const mm = String(date.getMonth() + 1).padStart(2, '0');
  const yyyy = date.getFullYear();
  return `${dd}/${mm}/${yyyy}`;
}

function isVideoContent(item: GeneratedContent): boolean {
  if ((item.mediaType ?? 'IMAGE').toUpperCase() === 'VIDEO') return true;
  const assets = item.assets ?? [];
  if (!assets.length) return false;
  return assets.some((asset) => (asset.type ?? 'IMAGE').toUpperCase() === 'VIDEO');
}

function isImageContent(item: GeneratedContent): boolean {
  if ((item.mediaType ?? 'IMAGE').toUpperCase() === 'VIDEO') return false;
  if (item.status === 'GENERATING' || item.status === 'PUBLISHING') {
    return !isVideoContent(item);
  }
  const assets = item.assets ?? [];
  if (!assets.length) return false;
  return assets.every((asset) => (asset.type ?? 'IMAGE').toUpperCase() !== 'VIDEO');
}

interface LightboxMedia {
  url: string;
  video: boolean;
  label?: string;
}

function MediaLightbox({
  media,
  onClose,
}: {
  media: LightboxMedia;
  onClose: () => void;
}) {
  useEffect(() => {
    function onKey(event: KeyboardEvent) {
      if (event.key === 'Escape') onClose();
    }
    window.addEventListener('keydown', onKey);
    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    return () => {
      window.removeEventListener('keydown', onKey);
      document.body.style.overflow = previousOverflow;
    };
  }, [onClose]);

  return (
    <div
      role="dialog"
      aria-modal="true"
      aria-label={media.label || 'Vista ampliada'}
      className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-8"
      onClick={onClose}
    >
      <div className="absolute inset-0 bg-black/82" />
      <button
        type="button"
        onClick={onClose}
        className="absolute top-4 right-4 z-20 rounded-full bg-white/15 hover:bg-white/25 text-white w-10 h-10 inline-flex items-center justify-center text-lg"
        aria-label="Cerrar"
      >
        ×
      </button>
      <div
        className="relative z-10 max-h-[92vh] max-w-[min(96vw,1120px)]"
        onClick={(event) => event.stopPropagation()}
      >
        {media.video ? (
          <video
            src={media.url}
            className="max-h-[92vh] max-w-full rounded-xl shadow-2xl bg-black"
            controls
            autoPlay
            playsInline
          />
        ) : (
          // eslint-disable-next-line @next/next/no-img-element
          <img
            src={media.url}
            alt={media.label || 'Imagen generada'}
            className="max-h-[92vh] max-w-full rounded-xl shadow-2xl object-contain bg-black"
          />
        )}
      </div>
    </div>
  );
}

export function ContentCreator() {
  const queryClient = useQueryClient();
  const [objective, setObjective] = useState<string>('AUTOMATIC');
  const [channels, setChannels] = useState<string[]>([
    'INSTAGRAM_FEED',
    'INSTAGRAM_STORY',
  ]);
  const [instructions, setInstructions] = useState('');
  const [serviceId, setServiceId] = useState('');
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [editCaption, setEditCaption] = useState('');
  const [editHeadline, setEditHeadline] = useState('');
  const [editCta, setEditCta] = useState('');
  const [references, setReferences] = useState<ReferencePreview[]>([]);
  const [publishChannels, setPublishChannels] = useState<string[]>([]);

  const [autoEnabled, setAutoEnabled] = useState(false);
  const [autoDays, setAutoDays] = useState<number[]>([1, 2, 3, 4, 5]);
  const [autoTime, setAutoTime] = useState('10:00');
  const [autoChannels, setAutoChannels] = useState<string[]>([
    'INSTAGRAM_STORY',
    'INSTAGRAM_FEED',
  ]);
  const [autoObjective, setAutoObjective] = useState('AUTOMATIC');
  const [notifyWhatsAppPhone, setNotifyWhatsAppPhone] = useState('');
  const [notifyEmail, setNotifyEmail] = useState('');
  const [autoDirty, setAutoDirty] = useState(false);
  const [mediaKind, setMediaKind] = useState<'image' | 'video'>('image');
  const [videoDuration, setVideoDuration] = useState<5 | 10 | 15>(5);
  const [lightbox, setLightbox] = useState<LightboxMedia | null>(null);

  const summary = useQuery({
    queryKey: ['content-summary'],
    queryFn: () => api<ContentSummary>('/admin/content/summary'),
  });

  const socialConfig = useQuery({
    queryKey: ['content-config'],
    queryFn: () => api<SocialContentConfig>('/admin/content/config'),
  });

  const list = useQuery({
    queryKey: ['content-list'],
    queryFn: () => api<GeneratedContent[]>('/admin/content'),
  });

  const business = useQuery({
    queryKey: ['current-business'],
    queryFn: () =>
      api<{ brandingConfig?: unknown | null; timezone?: string }>(
        '/admin/business',
      ),
  });

  const whatsapp = useQuery({
    queryKey: ['whatsapp-config'],
    queryFn: () => api<WhatsAppStatus | null>('/admin/whatsapp'),
  });
  const waConnected = whatsapp.data?.status === 'connected';

  const servicesQuery = useQuery({
    queryKey: ['services', 'enabled'],
    queryFn: () =>
      api<ServiceRow[]>('/admin/services?enabledOnly=true'),
  });

  useEffect(() => {
    if (!socialConfig.data || autoDirty) return;
    const cfg = socialConfig.data;
    setAutoEnabled(Boolean(cfg.autoGenerateEnabled));
    setAutoDays(
      cfg.autoGenerateDaysOfWeek?.length > 0
        ? cfg.autoGenerateDaysOfWeek
        : [1, 2, 3, 4, 5, 6, 7],
    );
    setAutoTime(cfg.autoGenerateTime || '10:00');
    setAutoChannels(
      cfg.autoGenerateChannels?.length > 0
        ? cfg.autoGenerateChannels
        : cfg.defaultChannels?.length > 0
          ? cfg.defaultChannels
          : ['INSTAGRAM_STORY', 'INSTAGRAM_FEED'],
    );
    setAutoObjective(cfg.autoGenerateObjective || 'AUTOMATIC');
    setNotifyWhatsAppPhone(cfg.notifyWhatsAppPhone || '');
    setNotifyEmail(cfg.notifyEmail || '');
  }, [socialConfig.data, autoDirty]);

  const selected = useQuery({
    queryKey: ['content', selectedId],
    enabled: Boolean(selectedId),
    queryFn: () => api<GeneratedContent>(`/admin/content/${selectedId}`),
  });

  const detail = selected.data ?? list.data?.find((c) => c.id === selectedId);

  function syncEditors(item: GeneratedContent | undefined) {
    if (!item) return;
    setEditCaption(item.caption ?? '');
    setEditHeadline(item.headline ?? '');
    setEditCta(item.cta ?? '');
    setPublishChannels(
      item.channels?.length ? [...item.channels] : ['INSTAGRAM_FEED'],
    );
  }

  function openContent(item: GeneratedContent) {
    setSelectedId(item.id);
    syncEditors(item);
    setReferences((prev) => {
      for (const ref of prev) {
        if (ref.local) URL.revokeObjectURL(ref.url);
      }
      return (item.referenceImageUrls ?? []).map((url, index) => ({
        id: `saved-${item.id}-${index}`,
        url,
        local: false,
      }));
    });
  }

  function addReferenceFiles(fileList: FileList | null) {
    if (!fileList?.length) return;
    const incoming = Array.from(fileList).filter((f) =>
      f.type.startsWith('image/'),
    );
    setReferences((prev) => {
      const room = Math.max(0, 4 - prev.length);
      const next = incoming.slice(0, room).map((file) => ({
        id: `local-${file.name}-${file.size}-${file.lastModified}`,
        file,
        url: URL.createObjectURL(file),
        local: true,
      }));
      return [...prev, ...next].slice(0, 4);
    });
  }

  function removeReference(id: string) {
    setReferences((prev) => {
      const target = prev.find((r) => r.id === id);
      if (target?.local) URL.revokeObjectURL(target.url);
      return prev.filter((r) => r.id !== id);
    });
  }

  async function resolveReferenceUrls(): Promise<string[]> {
    const alreadyUploaded = references
      .filter((r) => !r.local)
      .map((r) => r.url);
    const locals = references.filter((r) => r.local && r.file);
    if (!locals.length) return alreadyUploaded;

    const form = new FormData();
    for (const ref of locals) {
      if (ref.file) form.append('files', ref.file);
    }
    const uploaded = await apiForm<{ urls: string[] }>(
      '/admin/content/references',
      form,
    );
    return [...alreadyUploaded, ...(uploaded.urls ?? [])].slice(0, 4);
  }

  const generate = useMutation({
    mutationFn: async (payload: {
      objective: string;
      channels: string[];
      userInstructions?: string;
      serviceId?: string;
      contentId?: string;
    }) => {
      const referenceImageUrls = await resolveReferenceUrls();
      return api<GeneratedContent>('/admin/content/generate', {
        method: 'POST',
        body: JSON.stringify({
          ...payload,
          referenceImageUrls,
          mediaType: mediaKind === 'video' ? 'VIDEO' : 'IMAGE',
          ...(mediaKind === 'video' ? { durationSeconds: videoDuration } : {}),
        }),
      });
    },
    onSuccess: async (data) => {
      setSelectedId(data.id);
      syncEditors(data);
      setReferences(
        (data.referenceImageUrls ?? []).map((url, index) => ({
          id: `saved-${data.id}-${index}`,
          url,
          local: false,
        })),
      );
      await queryClient.invalidateQueries({ queryKey: ['content-list'] });
      await queryClient.invalidateQueries({ queryKey: ['content-summary'] });
      await queryClient.invalidateQueries({ queryKey: ['content', data.id] });
    },
  });

  const saveDraft = useMutation({
    mutationFn: async () => {
      if (!selectedId) throw new Error('Sin contenido');
      await api(`/admin/content/${selectedId}`, {
        method: 'PATCH',
        body: JSON.stringify({
          caption: editCaption,
          headline: editHeadline,
          cta: editCta,
        }),
      });
      return api(`/admin/content/${selectedId}/draft`, { method: 'POST' });
    },
    onSuccess: async () => {
      await queryClient.invalidateQueries({ queryKey: ['content-list'] });
      await queryClient.invalidateQueries({ queryKey: ['content', selectedId] });
      await queryClient.invalidateQueries({ queryKey: ['content-summary'] });
    },
  });

  const remove = useMutation({
    mutationFn: (id: string) =>
      api(`/admin/content/${id}`, { method: 'DELETE' }),
    onSuccess: async (_, id) => {
      if (selectedId === id) setSelectedId(null);
      await queryClient.invalidateQueries({ queryKey: ['content-list'] });
      await queryClient.invalidateQueries({ queryKey: ['content-summary'] });
    },
  });

  const publish = useMutation({
    mutationFn: async () => {
      if (!selectedId || !detail) throw new Error('Sin contenido');
      const channels =
        publishChannels.length > 0 ? publishChannels : detail.channels;
      if (!channels.length) {
        throw new Error('Seleccioná al menos un canal');
      }
      await api(`/admin/content/${selectedId}`, {
        method: 'PATCH',
        body: JSON.stringify({
          caption: editCaption,
          headline: editHeadline,
          cta: editCta,
          status: 'READY',
        }),
      });
      return api<GeneratedContent>(`/admin/content/${selectedId}/publish`, {
        method: 'POST',
        body: JSON.stringify({ channels }),
      });
    },
    onSuccess: async (data) => {
      syncEditors(data);
      await queryClient.invalidateQueries({ queryKey: ['content-list'] });
      await queryClient.invalidateQueries({ queryKey: ['content-summary'] });
      await queryClient.invalidateQueries({ queryKey: ['content', data.id] });
    },
  });

  function toggleChannel(value: string) {
    setChannels((prev) =>
      prev.includes(value)
        ? prev.filter((c) => c !== value)
        : [...prev, value],
    );
  }

  function togglePublishChannel(value: string) {
    setPublishChannels((prev) =>
      prev.includes(value)
        ? prev.filter((c) => c !== value)
        : [...prev, value],
    );
  }

  const saveAutoConfig = useMutation({
    mutationFn: () =>
      api<SocialContentConfig>('/admin/content/config', {
        method: 'PATCH',
        body: JSON.stringify({
          autoGenerateEnabled: autoEnabled,
          autoGenerateDaysOfWeek: autoDays,
          autoGenerateTime: autoTime,
          autoGenerateChannels: autoChannels,
          autoGenerateObjective: autoObjective,
          notifyWhatsAppPhone,
          notifyEmail,
        }),
      }),
    onSuccess: async () => {
      setAutoDirty(false);
      await queryClient.invalidateQueries({ queryKey: ['content-config'] });
    },
  });

  function toggleAutoDay(day: number) {
    setAutoDirty(true);
    setAutoDays((prev) => {
      if (prev.includes(day)) {
        if (prev.length <= 1) return prev;
        return prev.filter((d) => d !== day);
      }
      return [...prev, day].sort((a, b) => a - b);
    });
  }

  function toggleAutoChannel(value: string) {
    setAutoDirty(true);
    setAutoChannels((prev) =>
      prev.includes(value)
        ? prev.filter((c) => c !== value)
        : [...prev, value],
    );
  }

  const services = servicesQuery.data ?? [];
  const hasBranding = Boolean(business.data?.brandingConfig);
  const generating =
    generate.isPending ||
    detail?.status === 'GENERATING' ||
    detail?.status === 'PUBLISHING' ||
    publish.isPending;
  const canPublish =
    Boolean(selectedId) &&
    Boolean(detail?.assets?.length) &&
    publishChannels.length > 0 &&
    !['GENERATING', 'PUBLISHING'].includes(detail?.status ?? '') &&
    !publish.isPending;
  const previewItems = (list.data ?? []).filter(
    (item) =>
      Boolean(item.assets?.length) ||
      item.status === 'GENERATING' ||
      item.status === 'PUBLISHING',
  );
  const imageItems = previewItems.filter(isImageContent);
  const videoItems = previewItems.filter(isVideoContent);

  useEffect(() => {
    if (!selectedId) return;
    const selected = (list.data ?? []).find((item) => item.id === selectedId);
    if (!selected) return;
    const matchesTab =
      mediaKind === 'video' ? isVideoContent(selected) : isImageContent(selected);
    if (!matchesTab) setSelectedId(null);
  }, [mediaKind, selectedId, list.data]);

  function renderGallery(
    items: GeneratedContent[],
    emptyLabel: string,
  ) {
    return (
      <section className="space-y-3">
        <div className="flex items-end justify-between gap-2">
          <h3 className="font-medium">
            {mediaKind === 'image' ? 'Imágenes generadas' : 'Videos generados'}
          </h3>
          <p className="text-xs text-muted tabular-nums">
            {items.length} {items.length === 1 ? 'pieza' : 'piezas'}
          </p>
        </div>
        {list.isLoading ? (
          <p className="text-sm text-muted">Cargando…</p>
        ) : !items.length ? (
          <p className="text-sm text-muted panel rounded-2xl p-5">{emptyLabel}</p>
        ) : (
          <div className="grid gap-3 grid-cols-2 lg:grid-cols-3">
            {items.map((item) => {
              const thumb = item.assets?.[0]?.storageUrl;
              const thumbVideo = isVideoContent(item);
              const active = item.id === selectedId;
              return (
                <div
                  key={item.id}
                  className={`panel rounded-2xl overflow-hidden border transition ${
                    active
                      ? 'border-accent ring-1 ring-accent/40'
                      : 'border-transparent'
                  }`}
                >
                  <button
                    type="button"
                    onClick={() => {
                      openContent(item);
                      if (!thumb) return;
                      setLightbox({
                        url: thumb,
                        video: thumbVideo,
                        label: item.headline || item.topic || undefined,
                      });
                    }}
                    className={`block w-full text-left ${thumb ? 'cursor-zoom-in' : ''}`}
                  >
                    <div className="aspect-[4/3] bg-panel-2">
                      {thumb && thumbVideo ? (
                        <video
                          src={thumb}
                          className="w-full h-full object-cover pointer-events-none"
                          muted
                          playsInline
                          preload="metadata"
                        />
                      ) : thumb ? (
                        // eslint-disable-next-line @next/next/no-img-element
                        <img
                          src={thumb}
                          alt=""
                          className="w-full h-full object-cover"
                        />
                      ) : (
                        <div className="h-full flex items-center justify-center text-xs text-muted">
                          Generando…
                        </div>
                      )}
                    </div>
                  </button>
                  <button
                    type="button"
                    onClick={() => openContent(item)}
                    className="w-full text-left p-3 space-y-1"
                  >
                    <div className="flex items-center justify-between gap-2">
                      <p className="text-sm font-medium truncate">
                        {item.headline || item.topic || 'Sin título'}
                      </p>
                      <span
                        className={`shrink-0 text-[10px] font-medium px-1.5 py-0.5 rounded-full ${statusClass(item.status)}`}
                      >
                        {STATUS_LABEL[item.status] ?? item.status}
                      </span>
                    </div>
                    <p className="text-xs text-muted line-clamp-2">
                      {item.caption || '—'}
                    </p>
                  </button>
                </div>
              );
            })}
          </div>
        )}
      </section>
    );
  }

  return (
    <div className="space-y-6 max-w-6xl">
      <header className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <h2 className="text-2xl font-semibold tracking-tight">
            Creador de contenido
          </h2>
          <p className="text-sm text-muted mt-1">
            Generá borradores con IA y publicalos en WhatsApp Status o
            Instagram (Story / Feed / Reels).
          </p>
        </div>
        <Link
          href="/personalization"
          className="rounded-lg border border-line bg-panel px-3 py-2.5 text-sm min-h-10 inline-flex items-center"
        >
          {hasBranding ? 'Editar marca' : 'Configurar marca'}
        </Link>
      </header>

      <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">
        {[
          ['Este mes', summary.data?.generatedThisMonth],
          ['Sin publicar', summary.data?.drafts],
          ['Imágenes', summary.data?.imageGenerationsThisMonth],
          ['Videos', summary.data?.videoGenerationsThisMonth],
          [
            'Costo est.',
            summary.data
              ? `$${summary.data.estimatedCostThisMonth.toFixed(2)}`
              : undefined,
          ],
        ].map(([label, value]) => (
          <div key={String(label)} className="panel rounded-2xl p-4">
            <p className="text-xs text-muted uppercase tracking-wide">
              {label}
            </p>
            <p className="text-2xl font-semibold mt-1 tabular-nums">
              {value ?? '—'}
            </p>
          </div>
        ))}
      </section>

      <div
        className="inline-flex rounded-xl border border-line bg-panel p-1 gap-1"
        role="tablist"
        aria-label="Tipo de contenido"
      >
        <button
          type="button"
          role="tab"
          aria-selected={mediaKind === 'image'}
          onClick={() => {
            setMediaKind('image');
            setChannels(['INSTAGRAM_FEED', 'INSTAGRAM_STORY']);
          }}
          className={`inline-flex items-center gap-2 rounded-lg px-4 py-2.5 text-sm min-h-10 transition ${
            mediaKind === 'image'
              ? 'bg-accent text-white'
              : 'text-muted hover:text-text hover:bg-panel-2'
          }`}
        >
          Imagen
        </button>
        <button
          type="button"
          role="tab"
          aria-selected={mediaKind === 'video'}
          onClick={() => {
            setMediaKind('video');
            setChannels(['INSTAGRAM_REEL', 'INSTAGRAM_STORY', 'WHATSAPP_STATUS']);
          }}
          className={`inline-flex items-center gap-2 rounded-lg px-4 py-2.5 text-sm min-h-10 transition ${
            mediaKind === 'video'
              ? 'bg-accent text-white'
              : 'text-muted hover:text-text hover:bg-panel-2'
          }`}
        >
          Video
        </button>
      </div>

      <div className="space-y-6">
      <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(0,1.1fr)]">
        <section className="panel rounded-2xl p-5 space-y-4">
          <h3 className="font-medium">
            {mediaKind === 'video' ? 'Nuevo short' : 'Nuevo contenido'}
          </h3>
          {mediaKind === 'video' ? (
            <p className="text-sm text-muted">
              Short vertical 9:16. Se genera con kie.ai y, si está saturado,
              con fal.ai. Puede tardar unos minutos.
            </p>
          ) : null}
          {!hasBranding ? (
            <p className="text-sm text-amber-700 bg-amber-500/10 rounded-lg px-3 py-2">
              Tip: configurá la pestaña Marca en Personalización para mejores
              resultados.
            </p>
          ) : null}

          <label className="block space-y-1 text-sm">
            <span className="text-muted">Objetivo</span>
            <select
              className="w-full rounded-lg border border-line bg-panel px-3 py-2"
              value={objective}
              onChange={(e) => setObjective(e.target.value)}
            >
              {OBJECTIVES.map((o) => (
                <option key={o.value} value={o.value}>
                  {o.label}
                </option>
              ))}
            </select>
          </label>

          <div className="space-y-2 text-sm">
            <span className="text-muted">Canales</span>
            <div className="flex flex-wrap gap-2">
              {(mediaKind === 'video' ? VIDEO_CHANNELS : CHANNELS).map((ch) => {
                const on = channels.includes(ch.value);
                return (
                  <button
                    key={ch.value}
                    type="button"
                    onClick={() => toggleChannel(ch.value)}
                    className={`rounded-lg px-3 py-2 min-h-10 border text-sm ${
                      on
                        ? 'border-accent bg-accent/10 text-text'
                        : 'border-line text-muted'
                    }`}
                  >
                    {ch.label}
                  </button>
                );
              })}
            </div>
          </div>

          {mediaKind === 'video' ? (
            <div className="space-y-2 text-sm">
              <span className="text-muted">Duración</span>
              <div className="flex flex-wrap gap-2">
                {VIDEO_DURATIONS.map((seconds) => {
                  const on = videoDuration === seconds;
                  return (
                    <button
                      key={seconds}
                      type="button"
                      onClick={() => setVideoDuration(seconds)}
                      className={`rounded-lg px-3 py-2 min-h-10 border text-sm ${
                        on
                          ? 'border-accent bg-accent/10 text-text'
                          : 'border-line text-muted'
                      }`}
                    >
                      {seconds}s
                    </button>
                  );
                })}
              </div>
              {videoDuration === 15 ? (
                <p className="text-xs text-muted">
                  15s: Seedance (kie) genera hasta 12s. Kling en fal.ai, 10s.
                </p>
              ) : null}
            </div>
          ) : null}

          <label className="block space-y-1 text-sm">
            <span className="text-muted">Servicio (opcional)</span>
            <select
              className="w-full rounded-lg border border-line bg-panel px-3 py-2"
              value={serviceId}
              onChange={(e) => setServiceId(e.target.value)}
              disabled={servicesQuery.isLoading || services.length === 0}
            >
              <option value="">
                {servicesQuery.isLoading
                  ? 'Cargando servicios…'
                  : services.length === 0
                    ? 'No hay servicios cargados'
                    : 'Sin servicio específico'}
              </option>
              {services.map((s) => (
                <option key={s.id} value={s.id}>
                  {s.name}
                </option>
              ))}
            </select>
            {!servicesQuery.isLoading && services.length === 0 ? (
              <p className="text-xs text-muted">
                Cargá servicios en Personalización para poder asociarlos al
                contenido.
              </p>
            ) : null}
          </label>

          <label className="block space-y-1 text-sm">
            <span className="text-muted">Instrucciones</span>
            <textarea
              className="w-full min-h-28 rounded-lg border border-line bg-panel px-3 py-2"
              value={instructions}
              onChange={(e) => setInstructions(e.target.value)}
              placeholder="Ej. Promover manicura gel con 15% off esta semana…"
            />
          </label>

          <div className="space-y-2 text-sm">
            <div className="flex items-center justify-between gap-2">
              <span className="text-muted">
                Imágenes de referencia (opcional, máx. 4)
              </span>
              {references.length > 0 ? (
                <button
                  type="button"
                  className="text-xs text-muted hover:text-text"
                  onClick={() =>
                    setReferences((prev) => {
                      for (const ref of prev) {
                        if (ref.local) URL.revokeObjectURL(ref.url);
                      }
                      return [];
                    })
                  }
                >
                  Quitar todas
                </button>
              ) : null}
            </div>
            <p className="text-xs text-muted">
              Producto, local, logo o estilo. El modelo las usa para copy e
              imagen.
            </p>
            <input
              type="file"
              accept="image/*"
              multiple
              className="block w-full text-sm text-muted file:mr-3 file:rounded-lg file:border-0 file:bg-panel-2 file:px-3 file:py-2 file:text-sm file:text-text"
              onChange={(e) => {
                addReferenceFiles(e.target.files);
                e.target.value = '';
              }}
            />
            {references.length > 0 ? (
              <div className="grid grid-cols-4 gap-2">
                {references.map((ref) => (
                  <div
                    key={ref.id}
                    className="relative aspect-square rounded-lg overflow-hidden border border-line bg-panel-2"
                  >
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img
                      src={ref.url}
                      alt=""
                      className="w-full h-full object-cover"
                    />
                    <button
                      type="button"
                      onClick={() => removeReference(ref.id)}
                      className="absolute top-1 right-1 rounded bg-black/60 text-white text-[10px] px-1.5 py-0.5"
                    >
                      ✕
                    </button>
                  </div>
                ))}
              </div>
            ) : null}
          </div>

          <button
            type="button"
            disabled={generating || channels.length === 0}
            onClick={() =>
              generate.mutate({
                objective,
                channels,
                userInstructions: instructions.trim() || undefined,
                serviceId: serviceId || undefined,
              })
            }
            className="w-full rounded-lg bg-accent text-white px-3 py-2.5 text-sm font-medium disabled:opacity-60 min-h-10"
          >
            {generate.isPending
              ? mediaKind === 'video'
                ? 'Encolando short…'
                : 'Generando…'
              : mediaKind === 'video'
                ? 'Generar short'
                : 'Generar borrador'}
          </button>
          {generate.isError ? (
            <p className="text-sm text-red-600">
              {(generate.error as Error)?.message ||
                'No se pudo generar el contenido'}
            </p>
          ) : null}
        </section>

        <section className="panel rounded-2xl p-5 space-y-4 min-h-[28rem]">
          {!selectedId || !detail ? (
            <div className="h-full flex items-center justify-center text-sm text-muted py-16">
              Seleccioná un contenido o generá uno nuevo para ver el preview.
            </div>
          ) : (
            <>
              <div className="flex flex-wrap items-center justify-between gap-2">
                <div>
                  <h3 className="font-medium">
                    {detail.headline || detail.topic || 'Sin título'}
                  </h3>
                  <p className="text-xs text-muted mt-0.5">
                    {OBJECTIVES.find((o) => o.value === detail.objective)
                      ?.label ?? detail.objective}
                  </p>
                </div>
                <span
                  className={`text-[11px] font-medium px-2 py-0.5 rounded-full ${statusClass(detail.status)}`}
                >
                  {STATUS_LABEL[detail.status] ?? detail.status}
                </span>
              </div>

              {detail.error ? (
                <p className="text-sm text-red-600 bg-red-500/10 rounded-lg px-3 py-2">
                  {detail.error}
                </p>
              ) : null}

              <div className="grid gap-3 sm:grid-cols-2">
                {(detail.assets?.length ? detail.assets : []).map((asset) => {
                  const isVideo = (asset.type ?? 'IMAGE').toUpperCase() === 'VIDEO';
                  return (
                  <figure
                    key={asset.id}
                    className="rounded-xl overflow-hidden border border-line bg-panel-2"
                  >
                    {isVideo ? (
                      <video
                        src={asset.storageUrl}
                        className="w-full object-cover max-h-72"
                        controls
                        playsInline
                        preload="metadata"
                      />
                    ) : (
                      <button
                        type="button"
                        className="block w-full cursor-zoom-in"
                        onClick={() =>
                          setLightbox({
                            url: asset.storageUrl,
                            video: false,
                            label: asset.format,
                          })
                        }
                      >
                        {/* eslint-disable-next-line @next/next/no-img-element */}
                        <img
                          src={asset.storageUrl}
                          alt={asset.format}
                          className="w-full object-cover max-h-72"
                        />
                      </button>
                    )}
                    <figcaption className="px-2 py-1.5 text-[11px] text-muted">
                      {asset.format}
                    </figcaption>
                  </figure>
                  );
                })}
                {!detail.assets?.length && detail.status === 'GENERATING' ? (
                  <p className="text-sm text-muted sm:col-span-2">
                    Generando {mediaKind === 'video' ? 'video' : 'imagen'}…
                  </p>
                ) : null}
              </div>

              <label className="block space-y-1 text-sm">
                <span className="text-muted">Headline</span>
                <input
                  className="w-full rounded-lg border border-line bg-panel px-3 py-2"
                  value={editHeadline}
                  onChange={(e) => setEditHeadline(e.target.value)}
                />
              </label>
              <label className="block space-y-1 text-sm">
                <span className="text-muted">Caption</span>
                <textarea
                  className="w-full min-h-28 rounded-lg border border-line bg-panel px-3 py-2"
                  value={editCaption}
                  onChange={(e) => setEditCaption(e.target.value)}
                />
              </label>
              <label className="block space-y-1 text-sm">
                <span className="text-muted">CTA</span>
                <input
                  className="w-full rounded-lg border border-line bg-panel px-3 py-2"
                  value={editCta}
                  onChange={(e) => setEditCta(e.target.value)}
                />
              </label>

              <div className="rounded-xl border border-accent/30 bg-accent/5 p-4 space-y-3">
                <div>
                  <h4 className="font-medium text-sm">Publicar ahora</h4>
                  <p className="text-xs text-muted mt-1">
                    Elegí los canales. WhatsApp e Instagram deben estar
                    conectados en Integraciones.
                  </p>
                </div>
                <div className="flex flex-wrap gap-2">
                  {(mediaKind === 'video' ? VIDEO_CHANNELS : CHANNELS).map((ch) => {
                    const on = publishChannels.includes(ch.value);
                    return (
                      <button
                        key={ch.value}
                        type="button"
                        onClick={() => togglePublishChannel(ch.value)}
                        className={`rounded-lg px-3 py-2 min-h-10 border text-sm ${
                          on
                            ? 'border-accent bg-accent/15 text-text'
                            : 'border-line text-muted'
                        }`}
                      >
                        {ch.label}
                      </button>
                    );
                  })}
                </div>
                {!detail.assets?.length ? (
                  <p className="text-sm text-amber-700">
                    Este borrador todavía no tiene media. Esperá a que termine
                    la generación o regeneralo antes de publicar.
                  </p>
                ) : null}
                <button
                  type="button"
                  disabled={!canPublish}
                  onClick={() => {
                    const labels = publishChannels
                      .map((c) => CHANNEL_LABEL[c] ?? c)
                      .join(', ');
                    if (confirm(`¿Publicar ahora en: ${labels}?`)) {
                      publish.mutate();
                    }
                  }}
                  className="w-full rounded-lg bg-accent text-white px-3 py-3 text-sm font-semibold disabled:opacity-60 min-h-11"
                >
                  {publish.isPending || detail.status === 'PUBLISHING'
                    ? 'Publicando…'
                    : 'Publicar en canales seleccionados'}
                </button>
                {publish.isError ? (
                  <p className="text-sm text-red-600">
                    {(publish.error as Error)?.message ||
                      'No se pudo publicar el contenido'}
                  </p>
                ) : null}
              </div>

              <div className="flex flex-wrap gap-2">
                <button
                  type="button"
                  disabled={saveDraft.isPending}
                  onClick={() => saveDraft.mutate()}
                  className="rounded-lg border border-line bg-panel px-3 py-2.5 text-sm min-h-10 disabled:opacity-60"
                >
                  {saveDraft.isPending ? 'Guardando…' : 'Guardar borrador'}
                </button>
                <button
                  type="button"
                  disabled={generating}
                  onClick={() =>
                    generate.mutate({
                      objective: detail.objective,
                      channels: detail.channels,
                      userInstructions: instructions.trim() || undefined,
                      serviceId: detail.service?.id,
                      contentId: detail.id,
                    })
                  }
                  className="rounded-lg border border-line bg-panel px-3 py-2.5 text-sm min-h-10 disabled:opacity-60"
                >
                  Regenerar
                </button>
                <button
                  type="button"
                  disabled={remove.isPending}
                  onClick={() => {
                    if (confirm('¿Eliminar este contenido?')) {
                      remove.mutate(detail.id);
                    }
                  }}
                  className="rounded-lg border border-line bg-panel px-3 py-2.5 text-sm min-h-10 text-red-600"
                >
                  Eliminar
                </button>
              </div>
              {detail.publications?.length ? (
                <div className="space-y-1 rounded-lg border border-line bg-panel-2 p-3">
                  <p className="text-xs text-muted uppercase tracking-wide">
                    Historial de publicaciones
                  </p>
                  {detail.publications.map((pub) => {
                    const when = formatPubDate(pub.publishedAt);
                    return (
                      <p key={pub.id} className="text-sm">
                        {CHANNEL_LABEL[pub.channel] ?? pub.channel}:{' '}
                        <span className={statusClass(pub.status)}>
                          {STATUS_LABEL[pub.status] ?? pub.status}
                        </span>
                        {pub.status === 'PUBLISHED' && when ? (
                          <span className="text-muted"> · {when}</span>
                        ) : null}
                      </p>
                    );
                  })}
                </div>
              ) : null}
            </>
          )}
        </section>
      </div>

          {renderGallery(
            mediaKind === 'video' ? videoItems : imageItems,
            mediaKind === 'video'
              ? 'Todavía no hay videos generados. Creá un short arriba para verlo acá.'
              : 'Todavía no hay imágenes generadas. Creá un borrador arriba para verlo acá.',
          )}
        </div>

      <section className="panel rounded-2xl p-5 space-y-4">
        <div className="flex flex-wrap items-start justify-between gap-3">
          <div>
            <h3 className="font-medium">Generación automática</h3>
            <p className="text-sm text-muted mt-1">
              Elegí los días y la hora: generamos borradores solos en segundo
              plano, aunque no tengas el panel abierto. Quedan listos para que
              los revises y publiques.
              {business.data?.timezone
                ? ` Horario según ${business.data.timezone}.`
                : ''}
            </p>
          </div>
          <label className="inline-flex items-center gap-2 text-sm min-h-10 cursor-pointer">
            <input
              type="checkbox"
              className="h-4 w-4"
              checked={autoEnabled}
              onChange={(e) => {
                setAutoDirty(true);
                setAutoEnabled(e.target.checked);
              }}
            />
            Activar
          </label>
        </div>

        <div className="space-y-2">
          <div className="flex flex-wrap items-center gap-2">
            <span className="text-sm text-muted">Días</span>
            <button
              type="button"
              className="text-xs text-muted underline-offset-2 hover:underline"
              onClick={() => {
                setAutoDirty(true);
                setAutoDays([1, 2, 3, 4, 5, 6, 7]);
              }}
            >
              Todos
            </button>
            <button
              type="button"
              className="text-xs text-muted underline-offset-2 hover:underline"
              onClick={() => {
                setAutoDirty(true);
                setAutoDays([1, 2, 3, 4, 5]);
              }}
            >
              Lun–Vie
            </button>
          </div>
          <div className="flex flex-wrap gap-2">
            {WEEKDAYS.map((day) => {
              const on = autoDays.includes(day.value);
              return (
                <button
                  key={day.value}
                  type="button"
                  disabled={!autoEnabled}
                  onClick={() => toggleAutoDay(day.value)}
                  className={`rounded-lg border px-3 py-2 text-sm min-h-10 ${
                    on
                      ? 'border-accent bg-accent text-white'
                      : 'border-line text-muted'
                  } disabled:opacity-50`}
                >
                  {day.label}
                </button>
              );
            })}
          </div>
        </div>

        <div className="grid gap-4 sm:grid-cols-2">
          <label className="block space-y-1 text-sm">
            <span className="text-muted">Horario</span>
            <input
              type="time"
              disabled={!autoEnabled}
              className="w-full rounded-lg border border-line bg-panel px-3 py-2 disabled:opacity-50"
              value={autoTime}
              onChange={(e) => {
                setAutoDirty(true);
                setAutoTime(e.target.value);
              }}
            />
          </label>
          <label className="block space-y-1 text-sm">
            <span className="text-muted">Objetivo</span>
            <select
              disabled={!autoEnabled}
              className="w-full rounded-lg border border-line bg-panel px-3 py-2 disabled:opacity-50"
              value={autoObjective}
              onChange={(e) => {
                setAutoDirty(true);
                setAutoObjective(e.target.value);
              }}
            >
              {OBJECTIVES.map((item) => (
                <option key={item.value} value={item.value}>
                  {item.label}
                </option>
              ))}
            </select>
          </label>
        </div>

        <div className="space-y-2">
          <span className="text-sm text-muted">Canales</span>
          <div className="flex flex-wrap gap-2">
            {CHANNELS.map((ch) => {
              const on = autoChannels.includes(ch.value);
              return (
                <button
                  key={ch.value}
                  type="button"
                  disabled={!autoEnabled}
                  onClick={() => toggleAutoChannel(ch.value)}
                  className={`rounded-lg border px-3 py-2 text-sm min-h-10 ${
                    on
                      ? 'border-nav-active bg-nav-active/15 text-text'
                      : 'border-line text-muted'
                  } disabled:opacity-50`}
                >
                  {ch.label}
                </button>
              );
            })}
          </div>
        </div>

        <div className="rounded-xl border border-line/80 bg-bg/40 p-4 space-y-3">
          <div>
            <p className="text-sm font-medium">Avisos cuando se genera</p>
            <p className="text-xs text-muted mt-1">
              Si WhatsApp está conectado, te mandamos un mensaje al número.
              Si no, usamos el email.
            </p>
          </div>
          <div className="flex flex-wrap items-center gap-2 text-xs">
            <span
              className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 ${
                waConnected
                  ? 'bg-emerald-500/15 text-emerald-800'
                  : 'bg-line/60 text-muted'
              }`}
            >
              <span
                className={`h-1.5 w-1.5 rounded-full ${
                  waConnected ? 'bg-emerald-600' : 'bg-muted'
                }`}
              />
              {waConnected ? 'WhatsApp conectado' : 'WhatsApp desconectado'}
            </span>
            {!waConnected ? (
              <Link
                href="/integrations"
                className="text-muted underline-offset-2 hover:underline"
              >
                Conectar en Integraciones
              </Link>
            ) : null}
          </div>
          <div className="grid gap-4 sm:grid-cols-2">
            <label className="block space-y-1 text-sm">
              <span className="text-muted">Número de WhatsApp</span>
              <input
                type="tel"
                inputMode="tel"
                placeholder="54911..."
                className="w-full rounded-lg border border-line bg-panel px-3 py-2 disabled:opacity-50"
                value={notifyWhatsAppPhone}
                onChange={(e) => {
                  setAutoDirty(true);
                  setNotifyWhatsAppPhone(e.target.value);
                }}
              />
              <span className="block text-xs text-muted">
                Con código de país, sin 0 ni 15. Ej. 54911...
              </span>
            </label>
            <label className="block space-y-1 text-sm">
              <span className="text-muted">Email de respaldo</span>
              <input
                type="email"
                placeholder="vos@negocio.com"
                className="w-full rounded-lg border border-line bg-panel px-3 py-2 disabled:opacity-50"
                value={notifyEmail}
                onChange={(e) => {
                  setAutoDirty(true);
                  setNotifyEmail(e.target.value);
                }}
              />
              <span className="block text-xs text-muted">
                Se usa si WhatsApp no está conectado o el envío falla.
              </span>
            </label>
          </div>
        </div>

        <div className="flex flex-wrap items-center gap-3">
          <button
            type="button"
            className="rounded-lg bg-nav-active text-white px-4 py-2.5 text-sm min-h-10 disabled:opacity-50"
            disabled={
              saveAutoConfig.isPending ||
              (autoEnabled &&
                (autoDays.length === 0 || autoChannels.length === 0))
            }
            onClick={() => saveAutoConfig.mutate()}
          >
            {saveAutoConfig.isPending ? 'Guardando…' : 'Guardar programación'}
          </button>
          {socialConfig.data?.lastAutoGenerateAt ? (
            <p className="text-xs text-muted">
              Última automática:{' '}
              {formatPubDate(socialConfig.data.lastAutoGenerateAt)}
            </p>
          ) : null}
          {saveAutoConfig.isSuccess && !autoDirty ? (
            <p className="text-xs text-emerald-700">Guardado</p>
          ) : null}
          {saveAutoConfig.isError ? (
            <p className="text-xs text-red-600">
              {(saveAutoConfig.error as Error)?.message || 'No se pudo guardar'}
            </p>
          ) : null}
        </div>
      </section>
      {lightbox ? (
        <MediaLightbox media={lightbox} onClose={() => setLightbox(null)} />
      ) : null}
    </div>
  );
}
