import {
  BadRequestException,
  Body,
  Controller,
  Delete,
  Get,
  Param,
  Patch,
  Post,
  Query,
  UploadedFile,
  UploadedFiles,
  UseGuards,
  UseInterceptors,
} from '@nestjs/common';
import { FileInterceptor, FilesInterceptor } from '@nestjs/platform-express';
import { z } from 'zod';
import { ApiKeyGuard } from '../common/guards/api-key.guard';
import { ZodValidationPipe } from '../common/pipes/zod-validation.pipe';
import { ContentService } from './content.service';
import { ContentKnowledgeService } from './content-knowledge.service';

const contentStyleSchema = z.enum(['AUTO', 'EDUCATIONAL', 'COMEDY', 'SALES']);

const suggestBriefSchema = z.object({
  objective: z.string().min(1),
  channels: z.array(z.string()).optional(),
  userInstructions: z.string().max(2000).optional(),
  serviceId: z.string().uuid().optional(),
  mediaType: z.enum(['IMAGE', 'VIDEO']).optional(),
  durationSeconds: z
    .union([z.literal(5), z.literal(10), z.literal(15)])
    .optional(),
  contentStyle: contentStyleSchema.optional(),
});

const generateSchema = z.object({
  objective: z.string().min(1),
  channels: z.array(z.string()).min(1),
  userInstructions: z.string().max(2000).optional(),
  serviceId: z.string().uuid().optional(),
  contentId: z.string().uuid().optional(),
  referenceImageUrls: z.array(z.string().url()).max(4).optional(),
  mediaType: z.enum(['IMAGE', 'VIDEO']).optional(),
  durationSeconds: z
    .union([z.literal(5), z.literal(10), z.literal(15)])
    .optional(),
  contentStyle: contentStyleSchema.optional(),
});

const updateSchema = z.object({
  caption: z.string().max(2200).optional(),
  headline: z.string().max(200).optional(),
  cta: z.string().max(160).optional(),
  hashtags: z.array(z.string().max(40)).max(8).optional(),
  status: z.enum(['DRAFT', 'READY']).optional(),
});

const autoEditSchema = z
  .object({
    headline: z.string().max(200).optional(),
    cta: z.string().max(160).optional(),
    hook: z.string().max(200).optional(),
  })
  .default({});

const brandingSchema = z.object({
  logoUrl: z.union([z.string().url(), z.literal(''), z.null()]).optional(),
  primaryColor: z.string().max(32).nullable().optional(),
  secondaryColor: z.string().max(32).nullable().optional(),
  visualStyle: z.string().max(1000).nullable().optional(),
  commercialTone: z.string().max(500).nullable().optional(),
  targetAudience: z.string().max(500).nullable().optional(),
  preferNotes: z.string().max(2000).nullable().optional(),
  avoidNotes: z.string().max(2000).nullable().optional(),
  additionalInstructions: z.string().max(2000).nullable().optional(),
});

const socialConfigSchema = z.object({
  defaultChannels: z.array(z.string()).optional(),
  maxGenerationsPerDay: z.number().int().min(1).max(200).optional(),
  maxGenerationsPerMonth: z.number().int().min(1).max(2000).optional(),
  preferredObjectives: z.array(z.string()).optional(),
  autoGenerateEnabled: z.boolean().optional(),
  autoGenerateDaysOfWeek: z
    .array(z.number().int().min(1).max(7))
    .max(7)
    .optional(),
  autoGenerateTime: z
    .string()
    .regex(/^([01]?\d|2[0-3]):[0-5]\d$/, 'Usá formato HH:mm')
    .optional(),
  autoGenerateChannels: z.array(z.string()).optional(),
  autoGenerateObjective: z.string().min(1).optional(),
  notifyWhatsAppPhone: z
    .union([z.string().max(32), z.literal(''), z.null()])
    .optional(),
  notifyEmail: z
    .union([z.string().email().max(200), z.literal(''), z.null()])
    .optional(),
});

const publishSchema = z.object({
  channels: z.array(z.string()).min(1).optional(),
});

const contentNoteSchema = z.object({
  title: z.string().min(1).max(200),
  content: z.string().min(1).max(50_000),
  category: z.string().max(80).optional(),
});

const updateContentNoteSchema = z.object({
  title: z.string().min(1).max(200).optional(),
  content: z.string().min(1).max(50_000).optional(),
  category: z.string().max(80).optional(),
});

@Controller('admin/content')
@UseGuards(ApiKeyGuard)
export class ContentAdminController {
  constructor(
    private readonly content: ContentService,
    private readonly contentKnowledge: ContentKnowledgeService,
  ) {}

  @Get('summary')
  summary() {
    return this.content.summary();
  }

  @Get()
  list(@Query('status') status?: string) {
    return this.content.list({ status });
  }

  @Get('branding')
  getBranding() {
    return this.content.getBranding();
  }

  @Patch('branding')
  upsertBranding(
    @Body(new ZodValidationPipe(brandingSchema))
    body: z.infer<typeof brandingSchema>,
  ) {
    return this.content.upsertBranding({
      ...body,
      logoUrl: body.logoUrl === '' ? null : body.logoUrl,
    });
  }

  @Get('config')
  getConfig() {
    return this.content.getSocialConfig();
  }

  @Patch('config')
  upsertConfig(
    @Body(new ZodValidationPipe(socialConfigSchema))
    body: z.infer<typeof socialConfigSchema>,
  ) {
    return this.content.upsertSocialConfig({
      ...body,
      notifyWhatsAppPhone:
        body.notifyWhatsAppPhone === '' ? null : body.notifyWhatsAppPhone,
      notifyEmail: body.notifyEmail === '' ? null : body.notifyEmail,
    });
  }

  /** Lineamientos de contenido (KB separada del chat del agente). */
  @Get('knowledge')
  knowledgeWorkspace() {
    return this.contentKnowledge.getWorkspace();
  }

  @Post('knowledge/notes')
  createKnowledgeNote(
    @Body(new ZodValidationPipe(contentNoteSchema))
    body: z.infer<typeof contentNoteSchema>,
  ) {
    return this.contentKnowledge.createNote(body);
  }

  @Patch('knowledge/documents/:id')
  updateKnowledgeNote(
    @Param('id') id: string,
    @Body(new ZodValidationPipe(updateContentNoteSchema))
    body: z.infer<typeof updateContentNoteSchema>,
  ) {
    return this.contentKnowledge.updateNote(id, body);
  }

  @Delete('knowledge/documents/:id')
  deleteKnowledgeDocument(@Param('id') id: string) {
    return this.contentKnowledge.deleteDocument(id);
  }

  @Post('knowledge/documents/:id/reindex')
  reindexKnowledgeDocument(@Param('id') id: string) {
    return this.contentKnowledge.reindex(id);
  }

  @Post('knowledge/upload')
  @UseInterceptors(
    FileInterceptor('file', {
      limits: { fileSize: 12 * 1024 * 1024 },
    }),
  )
  uploadKnowledgeFile(
    @UploadedFile() file: Express.Multer.File,
    @Body() body: { title?: string },
  ) {
    return this.contentKnowledge.upload(file, body?.title);
  }

  @Post('branding/logo')
  @UseInterceptors(
    FileInterceptor('file', {
      limits: { fileSize: 8 * 1024 * 1024 },
    }),
  )
  uploadBrandingLogo(@UploadedFile() file: Express.Multer.File) {
    if (!file) {
      throw new BadRequestException('Subí un archivo de logo');
    }
    return this.content.uploadBrandingLogo(file);
  }

  @Post('references')
  @UseInterceptors(
    FilesInterceptor('files', 4, {
      limits: { fileSize: 8 * 1024 * 1024 },
    }),
  )
  uploadReferences(@UploadedFiles() files: Express.Multer.File[]) {
    return this.content.uploadReferenceImages(files ?? []);
  }

  @Post('suggest-brief')
  suggestBrief(
    @Body(new ZodValidationPipe(suggestBriefSchema))
    body: z.infer<typeof suggestBriefSchema>,
  ) {
    return this.content.suggestBrief(body);
  }

  @Post('generate')
  generate(
    @Body(new ZodValidationPipe(generateSchema))
    body: z.infer<typeof generateSchema>,
  ) {
    return this.content.generate(body);
  }

  @Get(':id')
  get(@Param('id') id: string) {
    return this.content.get(id);
  }

  @Post(':id/auto-edit')
  autoEdit(
    @Param('id') id: string,
    @Body(new ZodValidationPipe(autoEditSchema))
    body: z.infer<typeof autoEditSchema>,
  ) {
    return this.content.autoEdit(id, body);
  }

  @Post(':id/publish')
  publish(
    @Param('id') id: string,
    @Body(new ZodValidationPipe(publishSchema))
    body: z.infer<typeof publishSchema>,
  ) {
    return this.content.publish(id, body);
  }

  @Patch(':id')
  update(
    @Param('id') id: string,
    @Body(new ZodValidationPipe(updateSchema))
    body: z.infer<typeof updateSchema>,
  ) {
    return this.content.updateDraft(id, body);
  }

  @Post(':id/draft')
  saveDraft(@Param('id') id: string) {
    return this.content.saveDraft(id);
  }

  @Delete(':id')
  remove(@Param('id') id: string) {
    return this.content.remove(id);
  }
}
