import { InjectQueue } from '@nestjs/bullmq';
import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { Queue } from 'bullmq';
import { PrismaService } from '../common/prisma/prisma.service';
import {
  CONTENT_AUTO_JOB,
  CONTENT_AUTO_QUEUE,
  buildContentAutoCron,
  contentAutoJobId,
} from './content-auto-generate.queue';

/**
 * Cron real vía BullMQ Job Schedulers (Redis).
 * Dispara solo en el horario configurado; no hace polling.
 * Sigue funcionando con el admin cerrado mientras el API/Docker esté up.
 */
@Injectable()
export class ContentAutoGenerateScheduler implements OnModuleInit {
  private readonly logger = new Logger(ContentAutoGenerateScheduler.name);

  constructor(
    @InjectQueue(CONTENT_AUTO_QUEUE) private readonly queue: Queue,
    private readonly prisma: PrismaService,
  ) {}

  async onModuleInit() {
    await this.syncAll();
  }

  async syncAll() {
    const configs = await this.prisma.socialContentConfig.findMany({
      include: {
        business: { select: { id: true, timezone: true, name: true } },
      },
    });

    const wanted = new Set(
      configs
        .filter((c) => c.autoGenerateEnabled)
        .map((c) => contentAutoJobId(c.businessId)),
    );

    const existing = await this.queue.getJobSchedulers();
    for (const job of existing) {
      const id = job.id ?? '';
      if (id.startsWith('content-auto:') && !wanted.has(id)) {
        await this.queue.removeJobScheduler(id);
        this.logger.log(`Removed orphan cron ${id}`);
      }
    }

    for (const config of configs) {
      await this.syncBusiness(config.businessId);
    }

    this.logger.log(
      `Content auto-generate cron sync: ${wanted.size} job(s) activos`,
    );
  }

  async syncBusiness(businessId: string) {
    const config = await this.prisma.socialContentConfig.findUnique({
      where: { businessId },
      include: {
        business: { select: { timezone: true, name: true } },
      },
    });

    const schedulerId = contentAutoJobId(businessId);

    if (!config?.autoGenerateEnabled) {
      await this.queue.removeJobScheduler(schedulerId);
      return;
    }

    const tz =
      config.business.timezone?.trim() || 'America/Argentina/Buenos_Aires';
    const pattern = buildContentAutoCron(
      config.autoGenerateTime,
      config.autoGenerateDaysOfWeek,
    );
    if (!pattern) {
      this.logger.warn(
        `Cron inválido business=${businessId} time=${config.autoGenerateTime}`,
      );
      await this.queue.removeJobScheduler(schedulerId);
      return;
    }

    await this.queue.upsertJobScheduler(
      schedulerId,
      {
        pattern,
        tz,
      },
      {
        name: CONTENT_AUTO_JOB,
        data: { businessId },
        opts: {
          removeOnComplete: 20,
          removeOnFail: 50,
        },
      },
    );

    this.logger.log(
      `Cron registered business=${config.business.name} pattern="${pattern}" tz=${tz}`,
    );
  }
}
