const HAS_DIACRITIC = /[ÁÉÍÓÚÜÑáéíóúüñ]/;

/** Palabras que en español siempre llevan tilde/ñ; la forma sin tilde no es válida. */
const ACCENTED_WORDS: Record<string, string> = {
  ademas: 'además',
  atras: 'atrás',
  aqui: 'aquí',
  alli: 'allí',
  alla: 'allá',
  asi: 'así',
  tambien: 'también',
  despues: 'después',
  todavia: 'todavía',
  quizas: 'quizás',
  quiza: 'quizá',
  recien: 'recién',
  segun: 'según',
  jamas: 'jamás',
  detras: 'detrás',
  estan: 'están',
  estais: 'estáis',
  estabamos: 'estábamos',
  habiamos: 'habíamos',
  teniamos: 'teníamos',
  iamos: 'íbamos',
  eramos: 'éramos',
  facil: 'fácil',
  faciles: 'fáciles',
  dificil: 'difícil',
  dificiles: 'difíciles',
  rapido: 'rápido',
  rapida: 'rápida',
  rapidos: 'rápidos',
  rapidas: 'rápidas',
  rapidamente: 'rápidamente',
  facilmente: 'fácilmente',
  unicamente: 'únicamente',
  basicamente: 'básicamente',
  automaticamente: 'automáticamente',
  proximamente: 'próximamente',
  ultimo: 'último',
  ultima: 'última',
  ultimos: 'últimos',
  ultimas: 'últimas',
  unico: 'único',
  unica: 'única',
  unicos: 'únicos',
  unicas: 'únicas',
  basico: 'básico',
  basica: 'básica',
  basicos: 'básicos',
  basicas: 'básicas',
  tipico: 'típico',
  tipica: 'típica',
  tipicos: 'típicos',
  tipicas: 'típicas',
  historico: 'histórico',
  historica: 'histórica',
  historicos: 'históricos',
  historicas: 'históricas',
  economico: 'económico',
  economica: 'económica',
  economicos: 'económicos',
  economicas: 'económicas',
  automatico: 'automático',
  automatica: 'automática',
  automaticos: 'automáticos',
  automaticas: 'automáticas',
  electrico: 'eléctrico',
  electrica: 'eléctrica',
  electricos: 'eléctricos',
  electricas: 'eléctricas',
  proximo: 'próximo',
  proxima: 'próxima',
  proximos: 'próximos',
  proximas: 'próximas',
  maximo: 'máximo',
  maxima: 'máxima',
  maximos: 'máximos',
  maximas: 'máximas',
  minimo: 'mínimo',
  minima: 'mínima',
  minimos: 'mínimos',
  minimas: 'mínimas',
  dia: 'día',
  dias: 'días',
  cafe: 'café',
  cafes: 'cafés',
  menu: 'menú',
  menus: 'menús',
  telefono: 'teléfono',
  telefonos: 'teléfonos',
  codigo: 'código',
  codigos: 'códigos',
  sabado: 'sábado',
  sabados: 'sábados',
  miercoles: 'miércoles',
  linea: 'línea',
  lineas: 'líneas',
  maquina: 'máquina',
  maquinas: 'máquinas',
  musica: 'música',
  camara: 'cámara',
  camaras: 'cámaras',
  area: 'área',
  areas: 'áreas',
  epoca: 'época',
  epocas: 'épocas',
  metodo: 'método',
  metodos: 'métodos',
  credito: 'crédito',
  creditos: 'créditos',
  debito: 'débito',
  interes: 'interés',
  pais: 'país',
  paises: 'países',
  maiz: 'maíz',
  raiz: 'raíz',
  frio: 'frío',
  fria: 'fría',
  frios: 'fríos',
  frias: 'frías',
  comun: 'común',
  algun: 'algún',
  ningun: 'ningún',
  opinion: 'opinión',
  reunion: 'reunión',
  reuniones: 'reuniones',
  avion: 'avión',
  camion: 'camión',
  salon: 'salón',
  rincon: 'rincón',
  balcon: 'balcón',
  corazon: 'corazón',
  razon: 'razón',
  sazon: 'sazón',
  region: 'región',
  boton: 'botón',
  cajon: 'cajón',
  carton: 'cartón',
  jardin: 'jardín',
  sillon: 'sillón',
  colchon: 'colchón',
  manana: 'mañana',
  mananas: 'mañanas',
  senor: 'señor',
  senora: 'señora',
  senores: 'señores',
  senoras: 'señoras',
  dueno: 'dueño',
  duena: 'dueña',
  duenos: 'dueños',
  duenas: 'dueñas',
  nino: 'niño',
  nina: 'niña',
  ninos: 'niños',
  ninas: 'niñas',
  extrano: 'extraño',
  extrana: 'extraña',
  espanol: 'español',
  espanola: 'española',
  espana: 'españa',
  compania: 'compañía',
  companias: 'compañías',
  tenes: 'tenés',
  queres: 'querés',
  podes: 'podés',
  venis: 'venís',
  decis: 'decís',
  vivis: 'vivís',
  salis: 'salís',
  pedis: 'pedís',
  veni: 'vení',
  pedi: 'pedí',
  escribi: 'escribí',
  mostra: 'mostrá',
  peluqueria: 'peluquería',
  cafeteria: 'cafetería',
  libreria: 'librería',
  ferreteria: 'ferretería',
  panaderia: 'panadería',
  carniceria: 'carnicería',
  verduleria: 'verdulería',
  heladeria: 'heladería',
  pizzeria: 'pizzería',
  cerveceria: 'cervecería',
  confiteria: 'confitería',
  sabes: 'sabés',
  anio: 'año',
  anios: 'años',
  pagina: 'página',
  paginas: 'páginas',
  clinica: 'clínica',
  clinicas: 'clínicas',
  sesion: 'sesión',
  sesiones: 'sesiones',
  estetica: 'estética',
  exito: 'éxito',
  informacion: 'información',
  odontologo: 'odontólogo',
  odontologa: 'odontóloga',
  kinesiologo: 'kinesiólogo',
  kinesiologa: 'kinesióloga',
  psicologo: 'psicólogo',
  psicologa: 'psicóloga',
  oxigeno: 'oxígeno',
  atmosfera: 'atmósfera',
  hibrido: 'híbrido',
};

const SUFFIX_FIXES: Array<[RegExp, string]> = [
  [/cion$/, 'ción'],
  [/sion$/, 'sión'],
  [/isimos$/, 'ísimos'],
  [/isimas$/, 'ísimas'],
  [/isimo$/, 'ísimo'],
  [/isima$/, 'ísima'],
];

function applyCasing(source: string, target: string): string {
  if (source.length > 1 && source === source.toUpperCase()) {
    return target.toLocaleUpperCase('es-AR');
  }
  if (source[0] === source[0]?.toUpperCase()) {
    return target.charAt(0).toLocaleUpperCase('es-AR') + target.slice(1);
  }
  return target;
}

function restoreWord(word: string): string {
  if (HAS_DIACRITIC.test(word)) return word;

  const lower = word.toLowerCase();
  const fromDict = ACCENTED_WORDS[lower];
  if (fromDict) return applyCasing(word, fromDict);

  for (const [pattern, replacement] of SUFFIX_FIXES) {
    if (pattern.test(lower)) {
      return applyCasing(word, lower.replace(pattern, replacement));
    }
  }

  return word;
}

export function restoreSpanishOrthography(text: string): string {
  if (!text) return text;
  return text.replace(/[A-Za-zÁÉÍÓÚÜÑáéíóúüñ]+/g, restoreWord);
}

export function restoreQuotedSpanish(text: string): string {
  if (!text) return text;
  return text.replace(
    /(["“”«»'])([^"“”«»']+)\1/g,
    (_match, quote: string, inner: string) =>
      `${quote}${restoreSpanishOrthography(inner)}${quote}`,
  );
}

export const SPANISH_ORTHOGRAPHY_RULE = `- ORTOGRAFÍA (CRÍTICO): español rioplatense CON tildes, diéresis y ñ. Está PROHIBIDO devolver una palabra que lleva tilde sin tilde. Ejemplos: día (no dia), también (no tambien), fácil (no facil), atención (no atencion), promoción (no promocion), tenés (no tenes), sabés (no sabes), podés (no podes), menú, café, sábado, mañana. El bloque VOZ y ON-SCREEN se ven y se oyen en el video: sin tilde, el modelo lee mal. Revisá cada palabra antes de devolver.`;
